<a href="https://colab.research.google.com/github/tohnperfect/KKU_Data_Mining/blob/master/Pandas_101.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

![panda.jpg]()

## First, we have to say which packages we are going to use by <font color=green>import</font> them.

In [1]:
import pandas

## Connect with Google drive

In [2]:
from google.colab import drive
drive.mount('/content/drive')

path = '/content/drive/My Drive/DWDM_material'

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

## Create _path_ variables to store where is the data files

In [3]:
import os

In [4]:
search_click = os.path.join(path,'search_click.csv')
w_restaurant = os.path.join(path,'w_restaurant.csv')

## Then use _pandas_ to load the data into the environment

In [5]:
search_click_df = pandas.read_csv(search_click)

In [6]:
search_click_df.head()

  click_timestamp                             search_id  ...  time_diff_nanos   ads
0         11:38.9  5c004472-5ecc-4159-9698-9f329b8e26e1  ...     2.222400e+15  True
1         30:51.3  5f34eca0-c04e-4c10-b600-54aa447dbd8e  ...     4.608380e+14  True
2         32:09.6  8dc6d1f0-11f1-4239-9dd2-5c1674c81224  ...     2.581490e+15  True
3         00:59.8  1a5810e9-3d1f-44b9-9a2e-26ede21c524b  ...     1.404580e+15  True
4         23:36.8  6bc75e0d-fc65-471e-9926-ff6be6708639  ...     9.333590e+14  True

[5 rows x 6 columns]

In [7]:
w_restaurant_df = pandas.read_csv(w_restaurant)
w_restaurant_df.head()

   id              name  domain_id  ...  hotel_restaurant pet_friendly delivery
0   2  นครินทร์ทันตกรรม          2  ...               NaN          NaN      NaN
1   4      Corner House          1  ...               NaN          NaN      NaN
2   5    วัดโลกยสุธาราม          4  ...               NaN          NaN      NaN
3   6    นันท์คาราโอเกะ          1  ...               NaN          NaN      NaN
4   7       Buono Caffe          1  ...               NaN          NaN      NaN

[5 rows x 32 columns]

## To check if the dimension of loaded data is correct as described in the description

In [8]:
search_click_df.shape

(1048575, 6)

In [9]:
w_restaurant_df.shape

(246847, 32)

***

## It seem everything is ok, let's have fun with data

## 0. Point to data in the table

### normal indexing

In [10]:
search_click_df['search_id']

0          5c004472-5ecc-4159-9698-9f329b8e26e1
1          5f34eca0-c04e-4c10-b600-54aa447dbd8e
2          8dc6d1f0-11f1-4239-9dd2-5c1674c81224
3          1a5810e9-3d1f-44b9-9a2e-26ede21c524b
4          6bc75e0d-fc65-471e-9926-ff6be6708639
                           ...
1048570    99aab616-6fc5-4fbf-994b-4aebee7bb360
1048571    d70a2c5d-ee94-4e4c-9f7c-c5faac6db12a
1048572    4c1de7fe-300e-41aa-9d01-914344fc3753
1048573    2ec0ddec-e450-4b98-9779-42b77aa7eda5
1048574    5741d9cf-b9f1-441d-aa83-d2b0179bf874
Name: search_id, Length: 1048575, dtype: object

In [11]:
search_click_df['search_id'][0]

'5c004472-5ecc-4159-9698-9f329b8e26e1'

In [12]:
w_restaurant_df[['name','city_name','weighted_average_rating']]

                                        name  ... weighted_average_rating
0                           นครินทร์ทันตกรรม  ...                5.000000
1                               Corner House  ...                2.000000
2                             วัดโลกยสุธาราม  ...                4.000000
3                             นันท์คาราโอเกะ  ...                0.000000
4                                Buono Caffe  ...                3.738462
...                                      ...  ...                     ...
246842                            Sushi Tama  ...                3.663522
246843                     สะบายดี คาราโอเกะ  ...                0.000000
246844                      สเต็กแม่&กาแฟลูก  ...                4.000000
246845                              Mom Made  ...                5.000000
246846  ก๋วยเตี๋ยวหมูน้ำตก ก๋วยเตี๋ยวเรือทอง  ...                3.000000

[246847 rows x 3 columns]

### .iloc

In [13]:
search_click_df.iloc[0,1]

'5c004472-5ecc-4159-9698-9f329b8e26e1'

In [14]:
search_click_df.iloc[:10,:2]

  click_timestamp                             search_id
0         11:38.9  5c004472-5ecc-4159-9698-9f329b8e26e1
1         30:51.3  5f34eca0-c04e-4c10-b600-54aa447dbd8e
2         32:09.6  8dc6d1f0-11f1-4239-9dd2-5c1674c81224
3         00:59.8  1a5810e9-3d1f-44b9-9a2e-26ede21c524b
4         23:36.8  6bc75e0d-fc65-471e-9926-ff6be6708639
5         48:16.7  92ea02ba-2c89-4efd-973c-e23526c531de
6         39:18.4  79d61918-fb3e-4181-99b6-7a7abddfcdb1
7         33:39.0  7f8b2b57-dea1-4fe1-84c8-5a7d63750e47
8         07:48.3  3d9217bb-3eae-42b5-8cf3-a756efae2cfa
9         41:25.4  a2cb0d41-6e1f-4169-9140-cb671fbb41dc

## 1 Missing Values

In [15]:
search_click_df.isnull()

         click_timestamp  search_id  ...  time_diff_nanos    ads
0                  False      False  ...            False  False
1                  False      False  ...            False  False
2                  False      False  ...            False  False
3                  False      False  ...            False  False
4                  False      False  ...            False  False
...                  ...        ...  ...              ...    ...
1048570            False      False  ...            False  False
1048571            False      False  ...            False  False
1048572            False      False  ...            False  False
1048573            False      False  ...            False  False
1048574            False      False  ...            False  False

[1048575 rows x 6 columns]

In [16]:
search_click_df.isnull().any()

click_timestamp     False
search_id            True
business_id          True
display_position    False
time_diff_nanos     False
ads                 False
dtype: bool

## Handling missing values 1

In [17]:
search_click_df_nm = search_click_df.dropna()

In [18]:
search_click_df_nm.isnull().any().any()

False

In [19]:
print(search_click_df.shape)
print(search_click_df_nm.shape)

(1048575, 6)
(1048206, 6)

## Excercise 1 ตรวจสอบว่า การลบข้อมูล missing ออก

## จากตาราง w_restarant จะทำให้ข้อมูลลดลงกี่ %

In [25]:
size_before_drop = w_restaurant_df.shape[0]
size_after_drop = w_restaurant_df.dropna().shape[0]

print(f'size before drop = {size_before_drop} \nsize after drop = {size_after_drop} \
    \nwhich is {100*((size_before_drop-size_after_drop)/size_before_drop)}')

size before drop = 246847
size after drop = 4
which is 99.99837956304918

## Method 1.5

In [26]:
w_restaurant_df.isnull().any()

id                         False
name                       False
domain_id                  False
closed                     False
city_name                  False
zipcode                     True
geohash                    False
new_open                   False
weighted_average_rating    False
number_of_chains            True
number_of_bookmarks         True
number_of_reviews          False
number_of_product_tags     False
total_number_of_views      False
number_of_checkins         False
number_of_menu_groups      False
number_of_menu_photos      False
category_name              False
price_range                 True
avg_price                   True
parking                     True
credit_card_accepted        True
good_for_groups             True
good_for_kids               True
bookable                    True
best_of_wongnai             True
wifi                        True
number_of_seats             True
music_venue                 True
hotel_restaurant            True
pet_friendly                True
delivery                    True
dtype: bool

In [27]:
w_restaurant_df.dropna(subset=['id','name','price_range']).shape

(180972, 32)

## Method 2 (raplace with reasonable value)

### we are replacing missing value in the number of chains with 0

In [28]:
w_restaurant_df[['number_of_chains']] = w_restaurant_df[['number_of_chains']].fillna(0)

In [29]:
w_restaurant_df.isnull().any()

id                         False
name                       False
domain_id                  False
closed                     False
city_name                  False
zipcode                     True
geohash                    False
new_open                   False
weighted_average_rating    False
number_of_chains           False
number_of_bookmarks         True
number_of_reviews          False
number_of_product_tags     False
total_number_of_views      False
number_of_checkins         False
number_of_menu_groups      False
number_of_menu_photos      False
category_name              False
price_range                 True
avg_price                   True
parking                     True
credit_card_accepted        True
good_for_groups             True
good_for_kids               True
bookable                    True
best_of_wongnai             True
wifi                        True
number_of_seats             True
music_venue                 True
hotel_restaurant            True
pet_friendly                True
delivery                    True
dtype: bool

# 1. Adding a field from other table
or merge the entire tables https://www.kaggle.com/crawford/python-merge-tutorial/#

## one selected column
### .map()

In [ ]:
search_click_df['bu_name'] = search_click_df['business_id'].map(w_restaurant_df.set_index('id')['name'])

In [ ]:
search_click_df

,click_timestamp,search_id,business_id,display_position,time_diff_nanos,ads,bu_name
0,2018-06-15 05:11:38.914154,5c004472-5ecc-4159-9698-9f329b8e26e1,298839.0,0,2222397704154000,True,ปูดองอันยอง Eight
1,2018-06-15 06:30:51.277476,5f34eca0-c04e-4c10-b600-54aa447dbd8e,171372.0,0,460838273476000,True,Yoshinoya
2,2018-06-15 06:32:09.558025,8dc6d1f0-11f1-4239-9dd2-5c1674c81224,16157.0,0,2581491438025000,True,The Hub Cafe and Eatery
3,2018-06-15 06:00:59.820390,1a5810e9-3d1f-44b9-9a2e-26ede21c524b,89741.0,1,1404578985390000,True,ซั่งไห่ เสี่ยวหลงเปา
4,2018-06-15 05:23:36.828525,6bc75e0d-fc65-471e-9926-ff6be6708639,189564.0,1,933358625525000,True,Yoshinoya
5,2018-06-15 05:48:16.670540,92ea02ba-2c89-4efd-973c-e23526c531de,16157.0,1,2958857086540000,True,The Hub Cafe and Eatery
6,2018-06-15 06:39:18.378022,79d61918-fb3e-4181-99b6-7a7abddfcdb1,89741.0,1,1716278058022000,True,ซั่งไห่ เสี่ยวหลงเปา
7,2018-06-15 06:33:38.950615,7f8b2b57-dea1-4fe1-84c8-5a7d63750e47,238270.0,1,307983383615000,True,ปูดองอันยอง Express
8,2018-06-15 06:07:48.293373,3d9217bb-3eae-42b5-8cf3-a756efae2cfa,112509.0,2,585304544373000,False,อบอร่อย
9,2018-06-15 06:41:25.365830,a2cb0d41-6e1f-4169-9140-cb671fbb41dc,112509.0,2,578449410830000,False,อบอร่อย
10,2018-06-15 04:57:57.114487,bc1ad55e-9009-4b26-8abd-6982978cbbcd,331572.0,3,147703752487000,False,Le Boeuf The Steak & Fries Bistro
11,2018-06-15 05:02:13.717390,3d9217bb-3eae-42b5-8cf3-a756efae2cfa,331572.0,3,581369938390000,False,Le Boeuf The Steak & Fries Bistro
12,2018-06-15 05:12:27.210981,7f55a811-7827-4c49-86a6-52cb0c02eb90,331572.0,3,471852218981000,False,Le Boeuf The Steak & Fries Bistro
13,2018-06-15 06:11:07.020884,3d9217bb-3eae-42b5-8cf3-a756efae2cfa,331572.0,3,585503241884000,False,Le Boeuf The Steak & Fries Bistro
14,2018-06-15 04:58:28.867936,db1dfa8f-6a3a-4bd7-b9bd-ffd17cbfec0f,273486.0,4,104561033936000,False,Bankara Ramen
15,2018-06-15 05:49:16.946393,0cf0872e-e6a4-4fbb-a71a-1cebd62d97fc,275943.0,4,2743135990393000,False,Bake a wish Japanese Homemade Cake
16,2018-06-15 06:37:41.373098,80675c9e-c7cd-4e54-9f38-034ff5cc180f,286196.0,5,606154211098000,False,Fillets
17,2018-06-15 06:38:15.980718,5b229f50-0b36-48c8-bb94-d2351611ebf8,250135.0,5,3247279715718000,False,Kosirae
18,2018-06-15 06:28:00.829863,7b3e98a3-71d5-413f-8ab5-fe62b435572c,275943.0,7,464458570863000,False,Bake a wish Japanese Homemade Cake
19,2018-06-15 06:58:10.186311,801c5dc9-5eb0-4333-a585-189bd9134ff1,125496.0,7,1347791581311000,False,Sushi Masa
20,2018-06-15 06:33:47.318876,0b3baa5d-1ce2-4f37-9ed2-337ccf39a81e,98956.0,8,1501138607876000,False,Arno's Butcher and Eatery
21,2018-06-15 05:30:30.866493,0b0cb8e9-0e3c-4b7b-8b8f-468bf75bc22c,199058.0,9,1705221684493000,False,Katsushin (かつ真)
22,2018-06-15 06:19:08.929452,a4b25240-a109-4c15-ba9f-42f27e55efad,98956.0,9,532315648452000,False,Arno's Butcher and Eatery
23,2018-06-15 06:46:57.082058,27c933f6-4b52-473a-a381-85ba5074c4a2,98956.0,9,550604997058000,False,Arno's Butcher and Eatery
24,2018-06-15 06:32:17.479651,829cca3c-5ae7-4359-b74b-821135a66d75,98956.0,9,467772042651000,False,Arno's Butcher and Eatery
25,2018-06-15 06:19:13.121808,1bea6e55-a3bf-4604-bbad-d16248876d3d,60155.0,9,2399275582808000,False,Chocolate Ville
26,2018-06-15 05:35:15.473216,bc1ad55e-9009-4b26-8abd-6982978cbbcd,199058.0,10,149942042216000,False,Katsushin (かつ真)
27,2018-06-15 05:51:57.818187,59f51461-f730-4eea-a38d-037b6d7edeb0,60155.0,10,1237675606187000,False,Chocolate Ville
28,2018-06-15 05:18:51.357792,2388ca79-4bab-4b7b-b3d8-692b1d7e6cf7,60155.0,10,1618106625792000,False,Chocolate Ville
29,2018-06-15 06:29:14.175581,b0b61792-7a46-4e20-87a8-c0894028f025,199058.0,10,343456938581000,False,Katsushin (かつ真)
...,...,...,...,...,...,...,...
7882007,2018-06-28 03:04:38.688831,fb294961-7655-48ac-863c-0622ac6eb213,189896.0,11,201684516831000,True,LE ROOT
7882008,2018-06-28 02:46:20.774890,fb6b26b1-42c8-4a0a-a18a-2e96b82dc978,244037.0,11,198392234890000,True,La Baguette
7882009,2018-06-28 03:06:19.660861,fb8bde4f-07dc-41e1-9eb0-5b1ee1bb23e3,164383.0,11,208542734861000,True,เลือดหมูคุณศรี
7882010,2018-06-28 04:36:17.821334,fbc1d0e2-561a-4c9f-a057-91de4719a159,29839.0,11,209855398334000,True,Gorilla Grill
7882011,2018-06-28 03:52:17.140538,fd05a947-0e26-4706-9363-ce7f909b66c1,240258.0,11,205050653538000,True,Coral Bungalows
7882012,2018-06-28 02:59:45.960274,fd7b0252-65b2-4019-9d10-0a59a85ab332,67265.0,11,207157503274000,True,Daddy's Antique Cafe & Restaurant
7882013,2018-06-28 04:28:46.122453,fddfded5-a6a2-45b1-8c9c-dc44e5c27b44,240033.0,11,209204432453000,True,Le Marin Restaurant
7882014,2018-06-28 03:20:15.729406,fe7cdab0-1abe-4a02-983f-d6bb57008b2c,172652.0,11,205187947406000,True,รื่นรส (Reunros)
7882015,2018-06-28 02:38:11.631020,fea45463-61d4-4309-a6f6-362c935cdb9e,16614.0,11,205023370020000,True,CORO Field Cafe
7882016,2018-06-28 01:45:36.191993,feb92541-2311-4002-b040-2e59e9eaa52c,93853.0,11,200776108993000,True,PABLO mini Cheese Tart
7882017,2018-06-28 01:31:52.451333,fed68a73-9567-47fb-bd92-8edecbe4bf8a,247196.0,11,198553207333000,True,Sushi Cyu & Carnival Yakiniku
7882018,2018-06-28 04:35:51.858498,ff12f77e-e90e-4267-bec6-0f5958183494,182530.0,11,212419460498000,True,หนานหยวน
7882019,2018-06-28 02:56:28.920305,ff1c8485-74fa-4986-bb49-600eb3869926,36765.0,11,207024388305000,True,หลินฟ้า
7882020,2018-06-28 02:36:42.750199,ff704c6a-9974-462e-9eb4-5c97f7a942f6,304669.0,11,202569029199000,True,Dripoly Cafe
7882021,2018-06-28 06:43:29.213547,3059ca8e-fb7a-4a1d-bd82-c1970ec4ec8f,164383.0,11,16710547000,True,เลือดหมูคุณศรี
7882022,2018-06-28 04:29:22.558914,488dad5a-5f38-4422-9c20-eb710d263cdc,269423.0,11,161675914000,True,Sushi Mori
7882023,2018-06-28 05:10:32.958794,49110256-777b-4e99-8b54-6fc13231788a,230281.0,11,106517794000,True,Food Universe Thai International Cuisine
7882024,2018-06-28 03:00:53.657497,4e70837c-69bc-477f-a1d7-26f534722dac,252499.0,11,9162497000,True,สองฝั่งคลอง
7882025,2018-06-28 02:10:14.300088,55d6ab77-2388-4beb-b0c3-94c57710922d,273596.0,11,8934088000,True,ต้นกล้า ฟ้าใส (Tonklar Facai)
7882026,2018-06-28 06:42:52.625642,58fef246-5a06-441a-b27e-2250ad5d47d7,304669.0,11,31291642000,True,Dripoly Cafe
7882027,2018-06-28 01:25:07.953185,5d6f18b4-c147-46a6-806d-92fbf4abadcf,100611.0,11,18259185000,True,Zood Zood
7882028,2018-06-28 05:35:18.653329,60bfb598-5c43-4e4e-98f4-e62bbe481546,240015.0,11,580967283329000,True,ลำดีตี้ขัวแดง
7882029,2018-06-28 02:20:15.685338,8e138254-4546-4c7d-b1c3-9a3917290d17,335110.0,11,55937338000,True,ปูไข่ดอง บาย ปองไคดู เดลิเวอรี่
7882030,2018-06-28 06:41:46.111283,9c0e3c40-56a2-4d5d-b54e-c4d88f89f008,250231.0,11,29000283000,True,Enjoy Coffee and Bistro
7882031,2018-06-28 06:11:26.260735,9c581fe0-2d5c-4a93-91a5-5ff27a6bb2e1,107671.0,11,249069735000,True,Meruto Sushi
7882032,2018-06-28 01:59:10.893735,9ecd2dc1-b6f6-486d-b751-33eb16c53951,16614.0,11,4366735000,True,CORO Field Cafe
7882033,2018-06-28 01:59:11.085196,9ecd2dc1-b6f6-486d-b751-33eb16c53951,16614.0,11,4558196000,True,CORO Field Cafe
7882034,2018-06-28 06:49:02.493141,d086453d-7fde-4766-af39-8205f0f0a4aa,19569.0,11,16961141000,True,Fat Belly Pattaya
7882035,2018-06-28 06:36:02.865507,d157eba1-15e6-4f7a-b090-27a311d976a0,227719.0,11,27917507000,True,The River Barn
7882036,2018-06-28 06:20:35.249050,fb09595c-26cf-4bf3-a51b-1a9b4dd2fe50,316442.0,11,86426050000,True,Deven Chef Restaurant :Indian Food

## merge two tables
### .merge()

In [ ]:
merged_table = search_click_df.merge(w_restaurant_df,how='left',left_on='business_id',right_on='id')

In [ ]:
merged_table

,click_timestamp,search_id,business_id,display_position,time_diff_nanos,ads,bu_name,id,name,domain_id,...,good_for_groups,good_for_kids,bookable,best_of_wongnai,wifi,number_of_seats,music_venue,hotel_restaurant,pet_friendly,delivery
0,2018-06-15 05:11:38.914154,5c004472-5ecc-4159-9698-9f329b8e26e1,298839.0,0,2222397704154000,True,ปูดองอันยอง Eight,298839.0,ปูดองอันยอง Eight,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0
1,2018-06-15 06:30:51.277476,5f34eca0-c04e-4c10-b600-54aa447dbd8e,171372.0,0,460838273476000,True,Yoshinoya,171372.0,Yoshinoya,1.0,...,NaN,NaN,NaN,NaN,0.0,3.0,NaN,NaN,NaN,1.0
2,2018-06-15 06:32:09.558025,8dc6d1f0-11f1-4239-9dd2-5c1674c81224,16157.0,0,2581491438025000,True,The Hub Cafe and Eatery,16157.0,The Hub Cafe and Eatery,1.0,...,NaN,NaN,NaN,NaN,2.0,3.0,NaN,NaN,NaN,NaN
3,2018-06-15 06:00:59.820390,1a5810e9-3d1f-44b9-9a2e-26ede21c524b,89741.0,1,1404578985390000,True,ซั่งไห่ เสี่ยวหลงเปา,89741.0,ซั่งไห่ เสี่ยวหลงเปา,1.0,...,NaN,NaN,NaN,NaN,1.0,2.0,NaN,NaN,NaN,1.0
4,2018-06-15 05:23:36.828525,6bc75e0d-fc65-471e-9926-ff6be6708639,189564.0,1,933358625525000,True,Yoshinoya,189564.0,Yoshinoya,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0
5,2018-06-15 05:48:16.670540,92ea02ba-2c89-4efd-973c-e23526c531de,16157.0,1,2958857086540000,True,The Hub Cafe and Eatery,16157.0,The Hub Cafe and Eatery,1.0,...,NaN,NaN,NaN,NaN,2.0,3.0,NaN,NaN,NaN,NaN
6,2018-06-15 06:39:18.378022,79d61918-fb3e-4181-99b6-7a7abddfcdb1,89741.0,1,1716278058022000,True,ซั่งไห่ เสี่ยวหลงเปา,89741.0,ซั่งไห่ เสี่ยวหลงเปา,1.0,...,NaN,NaN,NaN,NaN,1.0,2.0,NaN,NaN,NaN,1.0
7,2018-06-15 06:33:38.950615,7f8b2b57-dea1-4fe1-84c8-5a7d63750e47,238270.0,1,307983383615000,True,ปูดองอันยอง Express,238270.0,ปูดองอันยอง Express,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0
8,2018-06-15 06:07:48.293373,3d9217bb-3eae-42b5-8cf3-a756efae2cfa,112509.0,2,585304544373000,False,อบอร่อย,112509.0,อบอร่อย,1.0,...,NaN,NaN,NaN,2018.0,NaN,NaN,NaN,NaN,NaN,NaN
9,2018-06-15 06:41:25.365830,a2cb0d41-6e1f-4169-9140-cb671fbb41dc,112509.0,2,578449410830000,False,อบอร่อย,112509.0,อบอร่อย,1.0,...,NaN,NaN,NaN,2018.0,NaN,NaN,NaN,NaN,NaN,NaN
10,2018-06-15 04:57:57.114487,bc1ad55e-9009-4b26-8abd-6982978cbbcd,331572.0,3,147703752487000,False,Le Boeuf The Steak & Fries Bistro,331572.0,Le Boeuf The Steak & Fries Bistro,1.0,...,NaN,NaN,NaN,2018.0,2.0,4.0,NaN,NaN,NaN,NaN
11,2018-06-15 05:02:13.717390,3d9217bb-3eae-42b5-8cf3-a756efae2cfa,331572.0,3,581369938390000,False,Le Boeuf The Steak & Fries Bistro,331572.0,Le Boeuf The Steak & Fries Bistro,1.0,...,NaN,NaN,NaN,2018.0,2.0,4.0,NaN,NaN,NaN,NaN
12,2018-06-15 05:12:27.210981,7f55a811-7827-4c49-86a6-52cb0c02eb90,331572.0,3,471852218981000,False,Le Boeuf The Steak & Fries Bistro,331572.0,Le Boeuf The Steak & Fries Bistro,1.0,...,NaN,NaN,NaN,2018.0,2.0,4.0,NaN,NaN,NaN,NaN
13,2018-06-15 06:11:07.020884,3d9217bb-3eae-42b5-8cf3-a756efae2cfa,331572.0,3,585503241884000,False,Le Boeuf The Steak & Fries Bistro,331572.0,Le Boeuf The Steak & Fries Bistro,1.0,...,NaN,NaN,NaN,2018.0,2.0,4.0,NaN,NaN,NaN,NaN
14,2018-06-15 04:58:28.867936,db1dfa8f-6a3a-4bd7-b9bd-ffd17cbfec0f,273486.0,4,104561033936000,False,Bankara Ramen,273486.0,Bankara Ramen,1.0,...,NaN,NaN,NaN,2018.0,1.0,2.0,NaN,NaN,NaN,1.0
15,2018-06-15 05:49:16.946393,0cf0872e-e6a4-4fbb-a71a-1cebd62d97fc,275943.0,4,2743135990393000,False,Bake a wish Japanese Homemade Cake,275943.0,Bake a wish Japanese Homemade Cake,1.0,...,NaN,NaN,NaN,2018.0,NaN,NaN,NaN,NaN,NaN,NaN
16,2018-06-15 06:37:41.373098,80675c9e-c7cd-4e54-9f38-034ff5cc180f,286196.0,5,606154211098000,False,Fillets,286196.0,Fillets,1.0,...,NaN,NaN,NaN,2018.0,2.0,3.0,NaN,NaN,NaN,NaN
17,2018-06-15 06:38:15.980718,5b229f50-0b36-48c8-bb94-d2351611ebf8,250135.0,5,3247279715718000,False,Kosirae,250135.0,Kosirae,1.0,...,NaN,NaN,NaN,2018.0,0.0,5.0,NaN,NaN,NaN,NaN
18,2018-06-15 06:28:00.829863,7b3e98a3-71d5-413f-8ab5-fe62b435572c,275943.0,7,464458570863000,False,Bake a wish Japanese Homemade Cake,275943.0,Bake a wish Japanese Homemade Cake,1.0,...,NaN,NaN,NaN,2018.0,NaN,NaN,NaN,NaN,NaN,NaN
19,2018-06-15 06:58:10.186311,801c5dc9-5eb0-4333-a585-189bd9134ff1,125496.0,7,1347791581311000,False,Sushi Masa,125496.0,Sushi Masa,1.0,...,NaN,NaN,NaN,2018.0,NaN,NaN,NaN,NaN,NaN,NaN
20,2018-06-15 06:33:47.318876,0b3baa5d-1ce2-4f37-9ed2-337ccf39a81e,98956.0,8,1501138607876000,False,Arno's Butcher and Eatery,98956.0,Arno's Butcher and Eatery,1.0,...,NaN,NaN,NaN,2018.0,2.0,5.0,NaN,NaN,NaN,NaN
21,2018-06-15 05:30:30.866493,0b0cb8e9-0e3c-4b7b-8b8f-468bf75bc22c,199058.0,9,1705221684493000,False,Katsushin (かつ真),199058.0,Katsushin (かつ真),1.0,...,NaN,NaN,NaN,2018.0,NaN,2.0,NaN,NaN,NaN,NaN
22,2018-06-15 06:19:08.929452,a4b25240-a109-4c15-ba9f-42f27e55efad,98956.0,9,532315648452000,False,Arno's Butcher and Eatery,98956.0,Arno's Butcher and Eatery,1.0,...,NaN,NaN,NaN,2018.0,2.0,5.0,NaN,NaN,NaN,NaN
23,2018-06-15 06:46:57.082058,27c933f6-4b52-473a-a381-85ba5074c4a2,98956.0,9,550604997058000,False,Arno's Butcher and Eatery,98956.0,Arno's Butcher and Eatery,1.0,...,NaN,NaN,NaN,2018.0,2.0,5.0,NaN,NaN,NaN,NaN
24,2018-06-15 06:32:17.479651,829cca3c-5ae7-4359-b74b-821135a66d75,98956.0,9,467772042651000,False,Arno's Butcher and Eatery,98956.0,Arno's Butcher and Eatery,1.0,...,NaN,NaN,NaN,2018.0,2.0,5.0,NaN,NaN,NaN,NaN
25,2018-06-15 06:19:13.121808,1bea6e55-a3bf-4604-bbad-d16248876d3d,60155.0,9,2399275582808000,False,Chocolate Ville,60155.0,Chocolate Ville,1.0,...,NaN,NaN,NaN,2018.0,1.0,5.0,NaN,NaN,NaN,NaN
26,2018-06-15 05:35:15.473216,bc1ad55e-9009-4b26-8abd-6982978cbbcd,199058.0,10,149942042216000,False,Katsushin (かつ真),199058.0,Katsushin (かつ真),1.0,...,NaN,NaN,NaN,2018.0,NaN,2.0,NaN,NaN,NaN,NaN
27,2018-06-15 05:51:57.818187,59f51461-f730-4eea-a38d-037b6d7edeb0,60155.0,10,1237675606187000,False,Chocolate Ville,60155.0,Chocolate Ville,1.0,...,NaN,NaN,NaN,2018.0,1.0,5.0,NaN,NaN,NaN,NaN
28,2018-06-15 05:18:51.357792,2388ca79-4bab-4b7b-b3d8-692b1d7e6cf7,60155.0,10,1618106625792000,False,Chocolate Ville,60155.0,Chocolate Ville,1.0,...,NaN,NaN,NaN,2018.0,1.0,5.0,NaN,NaN,NaN,NaN
29,2018-06-15 06:29:14.175581,b0b61792-7a46-4e20-87a8-c0894028f025,199058.0,10,343456938581000,False,Katsushin (かつ真),199058.0,Katsushin (かつ真),1.0,...,NaN,NaN,NaN,2018.0,NaN,2.0,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7882007,2018-06-28 03:04:38.688831,fb294961-7655-48ac-863c-0622ac6eb213,189896.0,11,201684516831000,True,LE ROOT,189896.0,LE ROOT,1.0,...,1.0,1.0,1.0,NaN,1.0,2.0,0.0,0.0,NaN,1.0
7882008,2018-06-28 02:46:20.774890,fb6b26b1-42c8-4a0a-a18a-2e96b82dc978,244037.0,11,198392234890000,True,La Baguette,244037.0,La Baguette,1.0,...,1.0,1.0,1.0,NaN,1.0,4.0,NaN,NaN,NaN,NaN
7882009,2018-06-28 03:06:19.660861,fb8bde4f-07dc-41e1-9eb0-5b1ee1bb23e3,164383.0,11,208542734861000,True,เลือดหมูคุณศรี,164383.0,เลือดหมูคุณศรี,1.0,...,1.0,1.0,1.0,NaN,1.0,3.0,0.0,0.0,0.0,0.0
7882010,2018-06-28 04:36:17.821334,fbc1d0e2-561a-4c9f-a057-91de4719a159,29839.0,11,209855398334000,True,Gorilla Grill,29839.0,Gorilla Grill,1.0,...,NaN,NaN,NaN,NaN,NaN,4.0,NaN,NaN,NaN,1.0
7882011,2018-06-28 03:52:17.140538,fd05a947-0e26-4706-9363-ce7f909b66c1,240258.0,11,205050653538000,True,Coral Bungalows,240258.0,Coral Bungalows,1.0,...,1.0,1.0,1.0,NaN,1.0,3.0,0.0,1.0,0.0,0.0
7882012,2018-06-28 02:59:45.960274,fd7b0252-65b2-4019-9d10-0a59a85ab332,67265.0,11,207157503274000,True,Daddy's Antique Cafe & Restaurant,67265.0,Daddy's Antique Cafe & Restaurant,1.0,...,1.0,1.0,1.0,NaN,1.0,3.0,NaN,NaN,NaN,NaN
7882013,2018-06-28 04:28:46.122453,fddfded5-a6a2-45b1-8c9c-dc44e5c27b44,240033.0,11,209204432453000,True,Le Marin Restaurant,240033.0,Le Marin Restaurant,1.0,...,1.0,1.0,1.0,NaN,NaN,4.0,NaN,1.0,0.0,1.0
7882014,2018-06-28 03:20:15.729406,fe7cdab0-1abe-4a02-983f-d6bb57008b2c,172652.0,11,205187947406000,True,รื่นรส (Reunros),172652.0,รื่นรส (Reunros),1.0,...,NaN,NaN,NaN,NaN,1.0,3.0,NaN,NaN,NaN,NaN
7882015,2018-06-28 02:38:11.631020,fea45463-61d4-4309-a6f6-362c935cdb9e,16614.0,11,205023370020000,True,CORO Field Cafe,16614.0,CORO Field Cafe,1.0,...,NaN,NaN,NaN,NaN,2.0,3.0,NaN,NaN,NaN,NaN
7882016,2018-06-28 01:45:36.191993,feb92541-2311-4002-b040-2e59e9eaa52c,93853.0,11,200776108993000,True,PABLO mini Cheese Tart,93853.0,PABLO mini Cheese Tart,1.0,...,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,1.0
7882017,2018-06-28 01:31:52.451333,fed68a73-9567-47fb-bd92-8edecbe4bf8a,247196.0,11,198553207333000,True,Sushi Cyu & Carnival Yakiniku,247196.0,Sushi Cyu & Carnival Yakiniku,1.0,...,NaN,NaN,NaN,NaN,NaN,2.0,NaN,NaN,NaN,NaN
7882018,2018-06-28 04:35:51.858498,ff12f77e-e90e-4267-bec6-0f5958183494,182530.0,11,212419460498000,True,หนานหยวน,182530.0,หนานหยวน,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7882019,2018-06-28 02:56:28.920305,ff1c8485-74fa-4986-bb49-600eb3869926,36765.0,11,207024388305000,True,หลินฟ้า,36765.0,หลินฟ้า,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7882020,2018-06-28 02:36:42.750199,ff704c6a-9974-462e-9eb4-5c97f7a942f6,304669.0,11,202569029199000,True,Dripoly Cafe,304669.0,Dripoly Cafe,1.0,...,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN
7882021,2018-06-28 06:43:29.213547,3059ca8e-fb7a-4a1d-bd82-c1970ec4ec8f,164383.0,11,16710547000,True,เลือดหมูคุณศรี,164383.0,เลือดหมูคุณศรี,1.0,...,1.0,1.0,1.0,NaN,1.0,3.0,0.0,0.0,0.0,0.0
7882022,2018-06-28 04:29:22.558914,488dad5a-5f38-4422-9c20-eb710d263cdc,269423.0,11,161675914000,True,Sushi Mori,269423.0,Sushi Mori,1.0,...,NaN,NaN,NaN,2018.0,1.0,3.0,NaN,NaN,NaN,NaN
7882023,2018-06-28 05:10:32.958794,49110256-777b-4e99-8b54-6fc13231788a,230281.0,11,106517794000,True,Food Universe Thai International Cuisine,230281.0,Food Universe Thai International Cuisine,1.0,...,NaN,NaN,NaN,NaN,1.0,4.0,NaN,NaN,NaN,1.0
7882024,2018-06-28 03:00:53.657497,4e70837c-69bc-477f-a1d7-26f534722dac,252499.0,11,9162497000,True,สองฝั่งคลอง,252499.0,สองฝั่งคลอง,1.0,...,1.0,1.0,1.0,NaN,1.0,5.0,NaN,NaN,NaN,1.0
7882025,2018-06-28 02:10:14.300088,55d6ab77-2388-4beb-b0c3-94c57710922d,273596.0,11,8934088000,True,ต้นกล้า ฟ้าใส (Tonklar Facai),273596.0,ต้นกล้า ฟ้าใส (Tonklar Facai),1.0,...,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,1.0
7882026,2018-06-28 06:42:52.625642,58fef246-5a06-441a-b27e-2250ad5d47d7,304669.0,11,31291642000,True,Dripoly Cafe,304669.0,Dripoly Cafe,1.0,...,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN
7882027,2018-06-28 01:25:07.953185,5d6f18b4-c147-46a6-806d-92fbf4abadcf,100611.0,11,18259185000,True,Zood Zood,100611.0,Zood Zood,1.0,...,1.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7882028,2018-06-28 05:35:18.653329,60bfb598-5c43-4e4e-98f4-e62bbe481546,240015.0,11,580967283329000,True,ลำดีตี้ขัวแดง,240015.0,ลำดีตี้ขัวแดง,1.0,...,1.0,1.0,1.0,NaN,1.0,5.0,0.0,0.0,0.0,0.0
7882029,2018-06-28 02:20:15.685338,8e138254-4546-4c7d-b1c3-9a3917290d17,335110.0,11,55937338000,True,ปูไข่ดอง บาย ปองไคดู เดลิเวอรี่,335110.0,ปูไข่ดอง บาย ปองไคดู เดลิเวอรี่,1.0,...,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN
7882030,2018-06-28 06:41:46.111283,9c0e3c40-56a2-4d5d-b54e-c4d88f89f008,250231.0,11,29000283000,True,Enjoy Coffee and Bistro,250231.0,Enjoy Coffee and Bistro,1.0,...,1.0,1.0,NaN,NaN,2.0,2.0,NaN,NaN,NaN,NaN
7882031,2018-06-28 06:11:26.260735,9c581fe0-2d5c-4a93-91a5-5ff27a6bb2e1,107671.0,11,249069735000,True,Meruto Sushi,107671.0,Meruto Sushi,1.0,...,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN
7882032,2018-06-28 01:59:10.893735,9ecd2dc1-b6f6-486d-b751-33eb16c53951,16614.0,11,4366735000,True,CORO Field Cafe,16614.0,CORO Field Cafe,1.0,...,NaN,NaN,NaN,NaN,2.0,3.0,NaN,NaN,NaN,NaN
7882033,2018-06-28 01:59:11.085196,9ecd2dc1-b6f6-486d-b751-33eb16c53951,16614.0,11,4558196000,True,CORO Field Cafe,16614.0,CORO Field Cafe,1.0,...,NaN,NaN,NaN,NaN,2.0,3.0,NaN,NaN,NaN,NaN
7882034,2018-06-28 06:49:02.493141,d086453d-7fde-4766-af39-8205f0f0a4aa,19569.0,11,16961141000,True,Fat Belly Pattaya,19569.0,Fat Belly Pattaya,1.0,...,1.0,1.0,1.0,NaN,1.0,2.0,0.0,NaN,NaN,0.0
7882035,2018-06-28 06:36:02.865507,d157eba1-15e6-4f7a-b090-27a311d976a0,227719.0,11,27917507000,True,The River Barn,227719.0,The River Barn,1.0,...,1.0,NaN,NaN,NaN,1.0,4.0,NaN,NaN,NaN,NaN
7882036,2018-06-28 06:20:35.249050,fb09595c-26cf-4bf3-a51b-1a9b4dd2fe50,316442.0,11,86426050000,True,Deven Chef Restaurant :Indian Food,316442.0,Deven Chef Restaurant :Indian Food,1.0,...,NaN,NaN,NaN,NaN,1.0,2.0,NaN,NaN,NaN,1.0

### we should delete the _id_ column because it's a copy of *business_id*
.drop()

In [ ]:
merged_table.drop('id',axis=1) ##this is only view of the result. How to modify the real table?

,click_timestamp,search_id,business_id,display_position,time_diff_nanos,ads,bu_name,name,domain_id,closed,...,good_for_groups,good_for_kids,bookable,best_of_wongnai,wifi,number_of_seats,music_venue,hotel_restaurant,pet_friendly,delivery
0,2018-06-15 05:11:38.914154,5c004472-5ecc-4159-9698-9f329b8e26e1,298839.0,0,2222397704154000,True,ปูดองอันยอง Eight,ปูดองอันยอง Eight,1.0,False,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0
1,2018-06-15 06:30:51.277476,5f34eca0-c04e-4c10-b600-54aa447dbd8e,171372.0,0,460838273476000,True,Yoshinoya,Yoshinoya,1.0,False,...,NaN,NaN,NaN,NaN,0.0,3.0,NaN,NaN,NaN,1.0
2,2018-06-15 06:32:09.558025,8dc6d1f0-11f1-4239-9dd2-5c1674c81224,16157.0,0,2581491438025000,True,The Hub Cafe and Eatery,The Hub Cafe and Eatery,1.0,False,...,NaN,NaN,NaN,NaN,2.0,3.0,NaN,NaN,NaN,NaN
3,2018-06-15 06:00:59.820390,1a5810e9-3d1f-44b9-9a2e-26ede21c524b,89741.0,1,1404578985390000,True,ซั่งไห่ เสี่ยวหลงเปา,ซั่งไห่ เสี่ยวหลงเปา,1.0,False,...,NaN,NaN,NaN,NaN,1.0,2.0,NaN,NaN,NaN,1.0
4,2018-06-15 05:23:36.828525,6bc75e0d-fc65-471e-9926-ff6be6708639,189564.0,1,933358625525000,True,Yoshinoya,Yoshinoya,1.0,False,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0
5,2018-06-15 05:48:16.670540,92ea02ba-2c89-4efd-973c-e23526c531de,16157.0,1,2958857086540000,True,The Hub Cafe and Eatery,The Hub Cafe and Eatery,1.0,False,...,NaN,NaN,NaN,NaN,2.0,3.0,NaN,NaN,NaN,NaN
6,2018-06-15 06:39:18.378022,79d61918-fb3e-4181-99b6-7a7abddfcdb1,89741.0,1,1716278058022000,True,ซั่งไห่ เสี่ยวหลงเปา,ซั่งไห่ เสี่ยวหลงเปา,1.0,False,...,NaN,NaN,NaN,NaN,1.0,2.0,NaN,NaN,NaN,1.0
7,2018-06-15 06:33:38.950615,7f8b2b57-dea1-4fe1-84c8-5a7d63750e47,238270.0,1,307983383615000,True,ปูดองอันยอง Express,ปูดองอันยอง Express,1.0,False,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0
8,2018-06-15 06:07:48.293373,3d9217bb-3eae-42b5-8cf3-a756efae2cfa,112509.0,2,585304544373000,False,อบอร่อย,อบอร่อย,1.0,False,...,NaN,NaN,NaN,2018.0,NaN,NaN,NaN,NaN,NaN,NaN
9,2018-06-15 06:41:25.365830,a2cb0d41-6e1f-4169-9140-cb671fbb41dc,112509.0,2,578449410830000,False,อบอร่อย,อบอร่อย,1.0,False,...,NaN,NaN,NaN,2018.0,NaN,NaN,NaN,NaN,NaN,NaN
10,2018-06-15 04:57:57.114487,bc1ad55e-9009-4b26-8abd-6982978cbbcd,331572.0,3,147703752487000,False,Le Boeuf The Steak & Fries Bistro,Le Boeuf The Steak & Fries Bistro,1.0,False,...,NaN,NaN,NaN,2018.0,2.0,4.0,NaN,NaN,NaN,NaN
11,2018-06-15 05:02:13.717390,3d9217bb-3eae-42b5-8cf3-a756efae2cfa,331572.0,3,581369938390000,False,Le Boeuf The Steak & Fries Bistro,Le Boeuf The Steak & Fries Bistro,1.0,False,...,NaN,NaN,NaN,2018.0,2.0,4.0,NaN,NaN,NaN,NaN
12,2018-06-15 05:12:27.210981,7f55a811-7827-4c49-86a6-52cb0c02eb90,331572.0,3,471852218981000,False,Le Boeuf The Steak & Fries Bistro,Le Boeuf The Steak & Fries Bistro,1.0,False,...,NaN,NaN,NaN,2018.0,2.0,4.0,NaN,NaN,NaN,NaN
13,2018-06-15 06:11:07.020884,3d9217bb-3eae-42b5-8cf3-a756efae2cfa,331572.0,3,585503241884000,False,Le Boeuf The Steak & Fries Bistro,Le Boeuf The Steak & Fries Bistro,1.0,False,...,NaN,NaN,NaN,2018.0,2.0,4.0,NaN,NaN,NaN,NaN
14,2018-06-15 04:58:28.867936,db1dfa8f-6a3a-4bd7-b9bd-ffd17cbfec0f,273486.0,4,104561033936000,False,Bankara Ramen,Bankara Ramen,1.0,False,...,NaN,NaN,NaN,2018.0,1.0,2.0,NaN,NaN,NaN,1.0
15,2018-06-15 05:49:16.946393,0cf0872e-e6a4-4fbb-a71a-1cebd62d97fc,275943.0,4,2743135990393000,False,Bake a wish Japanese Homemade Cake,Bake a wish Japanese Homemade Cake,1.0,False,...,NaN,NaN,NaN,2018.0,NaN,NaN,NaN,NaN,NaN,NaN
16,2018-06-15 06:37:41.373098,80675c9e-c7cd-4e54-9f38-034ff5cc180f,286196.0,5,606154211098000,False,Fillets,Fillets,1.0,False,...,NaN,NaN,NaN,2018.0,2.0,3.0,NaN,NaN,NaN,NaN
17,2018-06-15 06:38:15.980718,5b229f50-0b36-48c8-bb94-d2351611ebf8,250135.0,5,3247279715718000,False,Kosirae,Kosirae,1.0,False,...,NaN,NaN,NaN,2018.0,0.0,5.0,NaN,NaN,NaN,NaN
18,2018-06-15 06:28:00.829863,7b3e98a3-71d5-413f-8ab5-fe62b435572c,275943.0,7,464458570863000,False,Bake a wish Japanese Homemade Cake,Bake a wish Japanese Homemade Cake,1.0,False,...,NaN,NaN,NaN,2018.0,NaN,NaN,NaN,NaN,NaN,NaN
19,2018-06-15 06:58:10.186311,801c5dc9-5eb0-4333-a585-189bd9134ff1,125496.0,7,1347791581311000,False,Sushi Masa,Sushi Masa,1.0,False,...,NaN,NaN,NaN,2018.0,NaN,NaN,NaN,NaN,NaN,NaN
20,2018-06-15 06:33:47.318876,0b3baa5d-1ce2-4f37-9ed2-337ccf39a81e,98956.0,8,1501138607876000,False,Arno's Butcher and Eatery,Arno's Butcher and Eatery,1.0,False,...,NaN,NaN,NaN,2018.0,2.0,5.0,NaN,NaN,NaN,NaN
21,2018-06-15 05:30:30.866493,0b0cb8e9-0e3c-4b7b-8b8f-468bf75bc22c,199058.0,9,1705221684493000,False,Katsushin (かつ真),Katsushin (かつ真),1.0,False,...,NaN,NaN,NaN,2018.0,NaN,2.0,NaN,NaN,NaN,NaN
22,2018-06-15 06:19:08.929452,a4b25240-a109-4c15-ba9f-42f27e55efad,98956.0,9,532315648452000,False,Arno's Butcher and Eatery,Arno's Butcher and Eatery,1.0,False,...,NaN,NaN,NaN,2018.0,2.0,5.0,NaN,NaN,NaN,NaN
23,2018-06-15 06:46:57.082058,27c933f6-4b52-473a-a381-85ba5074c4a2,98956.0,9,550604997058000,False,Arno's Butcher and Eatery,Arno's Butcher and Eatery,1.0,False,...,NaN,NaN,NaN,2018.0,2.0,5.0,NaN,NaN,NaN,NaN
24,2018-06-15 06:32:17.479651,829cca3c-5ae7-4359-b74b-821135a66d75,98956.0,9,467772042651000,False,Arno's Butcher and Eatery,Arno's Butcher and Eatery,1.0,False,...,NaN,NaN,NaN,2018.0,2.0,5.0,NaN,NaN,NaN,NaN
25,2018-06-15 06:19:13.121808,1bea6e55-a3bf-4604-bbad-d16248876d3d,60155.0,9,2399275582808000,False,Chocolate Ville,Chocolate Ville,1.0,False,...,NaN,NaN,NaN,2018.0,1.0,5.0,NaN,NaN,NaN,NaN
26,2018-06-15 05:35:15.473216,bc1ad55e-9009-4b26-8abd-6982978cbbcd,199058.0,10,149942042216000,False,Katsushin (かつ真),Katsushin (かつ真),1.0,False,...,NaN,NaN,NaN,2018.0,NaN,2.0,NaN,NaN,NaN,NaN
27,2018-06-15 05:51:57.818187,59f51461-f730-4eea-a38d-037b6d7edeb0,60155.0,10,1237675606187000,False,Chocolate Ville,Chocolate Ville,1.0,False,...,NaN,NaN,NaN,2018.0,1.0,5.0,NaN,NaN,NaN,NaN
28,2018-06-15 05:18:51.357792,2388ca79-4bab-4b7b-b3d8-692b1d7e6cf7,60155.0,10,1618106625792000,False,Chocolate Ville,Chocolate Ville,1.0,False,...,NaN,NaN,NaN,2018.0,1.0,5.0,NaN,NaN,NaN,NaN
29,2018-06-15 06:29:14.175581,b0b61792-7a46-4e20-87a8-c0894028f025,199058.0,10,343456938581000,False,Katsushin (かつ真),Katsushin (かつ真),1.0,False,...,NaN,NaN,NaN,2018.0,NaN,2.0,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7882007,2018-06-28 03:04:38.688831,fb294961-7655-48ac-863c-0622ac6eb213,189896.0,11,201684516831000,True,LE ROOT,LE ROOT,1.0,False,...,1.0,1.0,1.0,NaN,1.0,2.0,0.0,0.0,NaN,1.0
7882008,2018-06-28 02:46:20.774890,fb6b26b1-42c8-4a0a-a18a-2e96b82dc978,244037.0,11,198392234890000,True,La Baguette,La Baguette,1.0,False,...,1.0,1.0,1.0,NaN,1.0,4.0,NaN,NaN,NaN,NaN
7882009,2018-06-28 03:06:19.660861,fb8bde4f-07dc-41e1-9eb0-5b1ee1bb23e3,164383.0,11,208542734861000,True,เลือดหมูคุณศรี,เลือดหมูคุณศรี,1.0,False,...,1.0,1.0,1.0,NaN,1.0,3.0,0.0,0.0,0.0,0.0
7882010,2018-06-28 04:36:17.821334,fbc1d0e2-561a-4c9f-a057-91de4719a159,29839.0,11,209855398334000,True,Gorilla Grill,Gorilla Grill,1.0,False,...,NaN,NaN,NaN,NaN,NaN,4.0,NaN,NaN,NaN,1.0
7882011,2018-06-28 03:52:17.140538,fd05a947-0e26-4706-9363-ce7f909b66c1,240258.0,11,205050653538000,True,Coral Bungalows,Coral Bungalows,1.0,False,...,1.0,1.0,1.0,NaN,1.0,3.0,0.0,1.0,0.0,0.0
7882012,2018-06-28 02:59:45.960274,fd7b0252-65b2-4019-9d10-0a59a85ab332,67265.0,11,207157503274000,True,Daddy's Antique Cafe & Restaurant,Daddy's Antique Cafe & Restaurant,1.0,False,...,1.0,1.0,1.0,NaN,1.0,3.0,NaN,NaN,NaN,NaN
7882013,2018-06-28 04:28:46.122453,fddfded5-a6a2-45b1-8c9c-dc44e5c27b44,240033.0,11,209204432453000,True,Le Marin Restaurant,Le Marin Restaurant,1.0,False,...,1.0,1.0,1.0,NaN,NaN,4.0,NaN,1.0,0.0,1.0
7882014,2018-06-28 03:20:15.729406,fe7cdab0-1abe-4a02-983f-d6bb57008b2c,172652.0,11,205187947406000,True,รื่นรส (Reunros),รื่นรส (Reunros),1.0,False,...,NaN,NaN,NaN,NaN,1.0,3.0,NaN,NaN,NaN,NaN
7882015,2018-06-28 02:38:11.631020,fea45463-61d4-4309-a6f6-362c935cdb9e,16614.0,11,205023370020000,True,CORO Field Cafe,CORO Field Cafe,1.0,False,...,NaN,NaN,NaN,NaN,2.0,3.0,NaN,NaN,NaN,NaN
7882016,2018-06-28 01:45:36.191993,feb92541-2311-4002-b040-2e59e9eaa52c,93853.0,11,200776108993000,True,PABLO mini Cheese Tart,PABLO mini Cheese Tart,1.0,False,...,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,1.0
7882017,2018-06-28 01:31:52.451333,fed68a73-9567-47fb-bd92-8edecbe4bf8a,247196.0,11,198553207333000,True,Sushi Cyu & Carnival Yakiniku,Sushi Cyu & Carnival Yakiniku,1.0,False,...,NaN,NaN,NaN,NaN,NaN,2.0,NaN,NaN,NaN,NaN
7882018,2018-06-28 04:35:51.858498,ff12f77e-e90e-4267-bec6-0f5958183494,182530.0,11,212419460498000,True,หนานหยวน,หนานหยวน,1.0,False,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7882019,2018-06-28 02:56:28.920305,ff1c8485-74fa-4986-bb49-600eb3869926,36765.0,11,207024388305000,True,หลินฟ้า,หลินฟ้า,1.0,False,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7882020,2018-06-28 02:36:42.750199,ff704c6a-9974-462e-9eb4-5c97f7a942f6,304669.0,11,202569029199000,True,Dripoly Cafe,Dripoly Cafe,1.0,False,...,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN
7882021,2018-06-28 06:43:29.213547,3059ca8e-fb7a-4a1d-bd82-c1970ec4ec8f,164383.0,11,16710547000,True,เลือดหมูคุณศรี,เลือดหมูคุณศรี,1.0,False,...,1.0,1.0,1.0,NaN,1.0,3.0,0.0,0.0,0.0,0.0
7882022,2018-06-28 04:29:22.558914,488dad5a-5f38-4422-9c20-eb710d263cdc,269423.0,11,161675914000,True,Sushi Mori,Sushi Mori,1.0,False,...,NaN,NaN,NaN,2018.0,1.0,3.0,NaN,NaN,NaN,NaN
7882023,2018-06-28 05:10:32.958794,49110256-777b-4e99-8b54-6fc13231788a,230281.0,11,106517794000,True,Food Universe Thai International Cuisine,Food Universe Thai International Cuisine,1.0,False,...,NaN,NaN,NaN,NaN,1.0,4.0,NaN,NaN,NaN,1.0
7882024,2018-06-28 03:00:53.657497,4e70837c-69bc-477f-a1d7-26f534722dac,252499.0,11,9162497000,True,สองฝั่งคลอง,สองฝั่งคลอง,1.0,False,...,1.0,1.0,1.0,NaN,1.0,5.0,NaN,NaN,NaN,1.0
7882025,2018-06-28 02:10:14.300088,55d6ab77-2388-4beb-b0c3-94c57710922d,273596.0,11,8934088000,True,ต้นกล้า ฟ้าใส (Tonklar Facai),ต้นกล้า ฟ้าใส (Tonklar Facai),1.0,False,...,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,1.0
7882026,2018-06-28 06:42:52.625642,58fef246-5a06-441a-b27e-2250ad5d47d7,304669.0,11,31291642000,True,Dripoly Cafe,Dripoly Cafe,1.0,False,...,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN
7882027,2018-06-28 01:25:07.953185,5d6f18b4-c147-46a6-806d-92fbf4abadcf,100611.0,11,18259185000,True,Zood Zood,Zood Zood,1.0,False,...,1.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7882028,2018-06-28 05:35:18.653329,60bfb598-5c43-4e4e-98f4-e62bbe481546,240015.0,11,580967283329000,True,ลำดีตี้ขัวแดง,ลำดีตี้ขัวแดง,1.0,False,...,1.0,1.0,1.0,NaN,1.0,5.0,0.0,0.0,0.0,0.0
7882029,2018-06-28 02:20:15.685338,8e138254-4546-4c7d-b1c3-9a3917290d17,335110.0,11,55937338000,True,ปูไข่ดอง บาย ปองไคดู เดลิเวอรี่,ปูไข่ดอง บาย ปองไคดู เดลิเวอรี่,1.0,False,...,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN
7882030,2018-06-28 06:41:46.111283,9c0e3c40-56a2-4d5d-b54e-c4d88f89f008,250231.0,11,29000283000,True,Enjoy Coffee and Bistro,Enjoy Coffee and Bistro,1.0,False,...,1.0,1.0,NaN,NaN,2.0,2.0,NaN,NaN,NaN,NaN
7882031,2018-06-28 06:11:26.260735,9c581fe0-2d5c-4a93-91a5-5ff27a6bb2e1,107671.0,11,249069735000,True,Meruto Sushi,Meruto Sushi,1.0,False,...,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN
7882032,2018-06-28 01:59:10.893735,9ecd2dc1-b6f6-486d-b751-33eb16c53951,16614.0,11,4366735000,True,CORO Field Cafe,CORO Field Cafe,1.0,False,...,NaN,NaN,NaN,NaN,2.0,3.0,NaN,NaN,NaN,NaN
7882033,2018-06-28 01:59:11.085196,9ecd2dc1-b6f6-486d-b751-33eb16c53951,16614.0,11,4558196000,True,CORO Field Cafe,CORO Field Cafe,1.0,False,...,NaN,NaN,NaN,NaN,2.0,3.0,NaN,NaN,NaN,NaN
7882034,2018-06-28 06:49:02.493141,d086453d-7fde-4766-af39-8205f0f0a4aa,19569.0,11,16961141000,True,Fat Belly Pattaya,Fat Belly Pattaya,1.0,False,...,1.0,1.0,1.0,NaN,1.0,2.0,0.0,NaN,NaN,0.0
7882035,2018-06-28 06:36:02.865507,d157eba1-15e6-4f7a-b090-27a311d976a0,227719.0,11,27917507000,True,The River Barn,The River Barn,1.0,False,...,1.0,NaN,NaN,NaN,1.0,4.0,NaN,NaN,NaN,NaN
7882036,2018-06-28 06:20:35.249050,fb09595c-26cf-4bf3-a51b-1a9b4dd2fe50,316442.0,11,86426050000,True,Deven Chef Restaurant :Indian Food,Deven Chef Restaurant :Indian Food,1.0,False,...,NaN,NaN,NaN,NaN,1.0,2.0,NaN,NaN,NaN,1.0

In [ ]:
merged_table = merged_table.drop('id',axis=1)

# 2. Fill Null (NaN) value ; NaN = Not a Number

In [ ]:
w_restaurant_df['number_of_chains'] = w_restaurant_df['number_of_chains'].fillna(0)

In [ ]:
w_restaurant_df

,id,name,domain_id,closed,city_name,zipcode,geohash,new_open,weighted_average_rating,number_of_chains,...,good_for_groups,good_for_kids,bookable,best_of_wongnai,wifi,number_of_seats,music_venue,hotel_restaurant,pet_friendly,delivery
0,2,นครินทร์ทันตกรรม,2,False,Samut Songkhram,75000,w4rh7g3,0,5.000000,0.0,...,NaN,NaN,NaN,NaN,NaN,13.0,NaN,NaN,NaN,NaN
1,4,Corner House,1,False,Bangkok Metropolitan Region,12150,w4rx73h,0,2.000000,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,5,วัดโลกยสุธาราม,4,False,Phra Nakhon Si Ayutthaya,13000,w4x98jk,0,4.000000,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,6,นันท์คาราโอเกะ,1,False,Bangkok Metropolitan Region,10700.0,w4rqw9q,0,0.000000,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,7,Buono Caffe,1,False,Bangkok Metropolitan Region,10220,w4rx4gd,0,3.738462,0.0,...,NaN,NaN,NaN,NaN,1.0,2.0,NaN,NaN,NaN,NaN
5,14,บ้านมุมสบาย,1,False,Chon Buri,NaN,w4rgsyz,0,5.000000,0.0,...,1.0,1.0,1.0,NaN,1.0,5.0,1.0,0.0,0.0,0.0
6,15,Hing Fat Resteurant,1,False,New Territories,NaN,wecny4b,0,3.000000,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,16,Sazanami,1,False,Bangkok Metropolitan Region,10110,w4rw0sp,0,4.130435,0.0,...,1.0,1.0,NaN,NaN,NaN,2.0,NaN,NaN,NaN,NaN
8,20,ครัวทิพวัลย์,1,False,Krabi,81170.0,w1qe9m1,0,0.000000,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,21,นกน้ำเต้าหู้,1,False,Narathiwat,96000,w30kt51,0,3.000000,0.0,...,NaN,NaN,NaN,NaN,0.0,2.0,NaN,NaN,NaN,NaN
10,24,Rotee Me Chabu,1,False,Bangkok Metropolitan Region,12130,w4rx3ys,0,4.047619,0.0,...,1.0,1.0,1.0,NaN,0.0,2.0,NaN,NaN,NaN,NaN
11,27,แพอาหารธาราบุรี,1,False,Kanchanaburi,71000.0,w4qzbb4,0,3.568245,0.0,...,1.0,1.0,1.0,NaN,NaN,2.0,NaN,NaN,NaN,NaN
12,28,Milkcow,1,False,Singapore,NaN,w21z7he,0,5.000000,0.0,...,1.0,1.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,29,Jeep Came อาหารป่า & ดนตรี,1,False,Bangkok Metropolitan Region,NaN,w4rqvbq,0,0.000000,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,30,The Coffee Shop,1,False,เขาใหญ่,NaN,w4xbuyk,0,0.000000,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN
15,32,The Rabbit หมูกระทะนานาชาติ,1,False,Chon Buri,20110,w4rfc75,0,2.846154,0.0,...,1.0,1.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,34,Mott 32,1,False,New Territories,NaN,wecnvb0,0,4.513072,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,35,ก๋วยเตี๋ยวเย็นตาโฟเจ๊หมวย นครสวรรค์,1,False,Nakhon Sawan,60000,w4z1q7n,0,0.000000,0.0,...,1.0,1.0,0.0,NaN,1.0,3.0,NaN,NaN,NaN,NaN
18,36,ร้านผักบุ้งบิน,1,False,Phitsanulok,65000.0,w4zr9kq,0,1.000000,0.0,...,1.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,37,ลาวชง,1,False,Bangkok Metropolitan Region,73000,w4rnsdr,0,1.000000,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20,38,บะหมี่ ลูกชิ้นปลา,1,False,Bangkok Metropolitan Region,10100,w4rqpk8,0,3.055556,0.0,...,NaN,NaN,NaN,NaN,0.0,2.0,NaN,NaN,NaN,NaN
21,41,ธัญรส สาขา 27,1,False,Phitsanulok,65000.0,w4zr9vu,0,4.000000,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22,42,ข้าวขาหมู ป้าเพ็ญ,1,False,Bangkok Metropolitan Region,NaN,w4rx0fh,0,5.000000,0.0,...,NaN,NaN,NaN,NaN,NaN,2.0,NaN,NaN,NaN,NaN
23,44,OMG OH MY GELATO,1,False,Bangkok Metropolitan Region,NaN,w4rqytp,0,3.700000,0.0,...,1.0,1.0,0.0,NaN,0.0,0.0,NaN,NaN,NaN,NaN
24,45,ลุงตุ๊เจ้าเก่า,1,False,Phra Nakhon Si Ayutthaya,13110.0,w4x6htj,0,0.000000,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25,46,Music Cofe,1,False,Chiang Rai,57100,w5x1ccc,0,4.000000,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26,49,ขส. สเต็ก,1,False,Bangkok Metropolitan Region,10300.0,w4rqrwg,0,2.714286,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27,50,ร้านป้าเล็ก ก๋วยจั๊บ คลองบางหลวง,1,False,Bangkok Metropolitan Region,NaN,w4rqnk7,0,3.666667,0.0,...,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN
28,51,โรงแรมมนต์ระวีพาวิเลี่ยนรีสอร์ท,1,False,Phitsanulok,65000.0,w4zrc0c,0,0.000000,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN
29,52,A Day in Summer,1,False,Bangkok Metropolitan Region,10600.0,w4rqnwh,0,3.392344,0.0,...,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
246817,340007,Ruj's Coffee,1,False,Chiang Rai,NaN,w5x4116,0,2.627451,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
246818,340011,Coffman,1,False,Khon Kaen,40000,w6cjkqy,0,3.000000,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
246819,340015,ลากูนเทอเรซ,1,False,Surat Thani,84320,w1xnm05,0,0.000000,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
246820,340022,Riliro's,1,False,Ōsaka-fu,NaN,xn0m5qv,0,0.000000,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
246821,340024,ผู้ชายขายหอย,1,False,Bangkok Metropolitan Region,NaN,w4rwj1f,0,0.000000,0.0,...,1.0,1.0,1.0,NaN,2.0,2.0,NaN,NaN,NaN,NaN
246822,340025,Chang Xing,1,False,Bangkok Metropolitan Region,NaN,w4rqpwp,0,4.000000,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
246823,340027,Takumi-chaya,1,False,Gifu-ken,NaN,xn3tek5,0,4.000000,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
246824,340028,โรงแรมทาวน์อินทาวน์พัทยา,1,False,Chon Buri,20150.0,w4rc84b,0,0.000000,0.0,...,1.0,NaN,1.0,NaN,NaN,NaN,NaN,1.0,NaN,NaN
246825,340029,โค้งลาบเป็ด,1,False,Nakhon Phanom,48000.0,w74d8r1,0,0.000000,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
246826,340031,ลาบเขยยอง,1,False,Chiang Mai,NaN,w5q6ws4,0,3.000000,0.0,...,NaN,NaN,NaN,NaN,1.0,4.0,NaN,NaN,NaN,NaN
246827,340035,สำราญโภชนา อตก.,1,False,Bangkok Metropolitan Region,10900.0,w4rw2p8,0,4.483871,0.0,...,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN
246828,340036,แพอลิสา,1,False,Kanchanaburi,71000.0,w4qz9h0,0,0.000000,0.0,...,1.0,1.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
246829,340037,Fatboy's Burger Bar,1,False,Kamphaeng Phet,NaN,w4yv8z6,0,4.357143,0.0,...,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN
246830,340038,ดิ อิมพีเรียล หัวหิน บีชรีสอร์ท,3,False,Hua Hin,77110,w4ppdt8,0,0.000000,0.0,...,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,0.0,NaN
246831,340041,ครัวศาลายา,1,False,Bangkok Metropolitan Region,70110.0,w4rn1xk,0,0.000000,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
246832,340042,โชคดีกาแฟ,1,False,เขาใหญ่,25000,w62pfyd,0,5.000000,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
246833,340043,เบอร์นีบาร์,1,False,Surat Thani,84140,w1xjusn,0,0.000000,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
246834,340048,Kuppadeli,1,True,Bangkok Metropolitan Region,10110,w4rw0e8,0,0.000000,5.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
246835,340051,ร้านครัวแกงป่า,1,False,Bangkok Metropolitan Region,11110.0,w4rr7tm,0,0.000000,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
246836,340054,คนึงหา,1,False,Phatthalung,NaN,w1r5m7j,0,4.000000,0.0,...,1.0,1.0,0.0,NaN,1.0,2.0,NaN,NaN,NaN,NaN
246837,340056,บึงกาฬลาบก้อย,1,False,Bueng Kan,38000.0,w738qxw,0,0.000000,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
246838,340059,ลีลาวดี,1,False,Rayong,20180.0,w4rb77u,0,0.000000,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
246839,340060,ส้มตำเวียงจันทร์,1,False,Lampang,NaN,w5qb02b,1,3.032258,0.0,...,NaN,NaN,NaN,NaN,0.0,2.0,NaN,NaN,NaN,NaN
246840,340063,โตข้าวต้มปลา,1,False,Bangkok Metropolitan Region,NaN,w4rmur2,0,0.000000,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
246841,340067,Toffy home,1,False,Phetchabun,67000,w4zvmve,0,3.000000,0.0,...,1.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
246842,340068,Sushi Tama,1,False,Bangkok Metropolitan Region,11130,w4rqtcb,0,3.663522,3.0,...,0.0,1.0,0.0,NaN,0.0,NaN,NaN,NaN,NaN,NaN
246843,340070,สะบายดี คาราโอเกะ,1,False,Bangkok Metropolitan Region,NaN,w4rwjcg,0,0.000000,0.0,...,1.0,NaN,1.0,NaN,NaN,2.0,NaN,NaN,NaN,NaN
246844,340074,สเต็กแม่&กาแฟลูก,1,False,Bangkok Metropolitan Region,10160,w4rmvxf,0,4.000000,0.0,...,1.0,1.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
246845,340079,Mom Made,1,False,Nakhon Si Thammarat,80000,w1x04g6,0,5.000000,0.0,...,1.0,1.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
246846,340091,ก๋วยเตี๋ยวหมูน้ำตก ก๋วยเตี๋ยวเรือทอง,1,False,Suphan Buri,72000,w4x4q7s,0,3.000000,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

# 3. Delete a record with Null value at the specific field
https://stackoverflow.com/questions/13413590/how-to-drop-rows-of-pandas-dataframe-whose-value-in-certain-columns-is-nan

In [ ]:
w_restaurant_df = w_restaurant_df.dropna(subset=['number_of_seats'])

In [ ]:
w_restaurant_df

,id,name,domain_id,closed,city_name,zipcode,geohash,new_open,weighted_average_rating,number_of_chains,...,good_for_groups,good_for_kids,bookable,best_of_wongnai,wifi,number_of_seats,music_venue,hotel_restaurant,pet_friendly,delivery
0,2,นครินทร์ทันตกรรม,2,False,Samut Songkhram,75000,w4rh7g3,0,5.000000,0.0,...,NaN,NaN,NaN,NaN,NaN,13.0,NaN,NaN,NaN,NaN
4,7,Buono Caffe,1,False,Bangkok Metropolitan Region,10220,w4rx4gd,0,3.738462,0.0,...,NaN,NaN,NaN,NaN,1.0,2.0,NaN,NaN,NaN,NaN
5,14,บ้านมุมสบาย,1,False,Chon Buri,NaN,w4rgsyz,0,5.000000,0.0,...,1.0,1.0,1.0,NaN,1.0,5.0,1.0,0.0,0.0,0.0
7,16,Sazanami,1,False,Bangkok Metropolitan Region,10110,w4rw0sp,0,4.130435,0.0,...,1.0,1.0,NaN,NaN,NaN,2.0,NaN,NaN,NaN,NaN
9,21,นกน้ำเต้าหู้,1,False,Narathiwat,96000,w30kt51,0,3.000000,0.0,...,NaN,NaN,NaN,NaN,0.0,2.0,NaN,NaN,NaN,NaN
10,24,Rotee Me Chabu,1,False,Bangkok Metropolitan Region,12130,w4rx3ys,0,4.047619,0.0,...,1.0,1.0,1.0,NaN,0.0,2.0,NaN,NaN,NaN,NaN
11,27,แพอาหารธาราบุรี,1,False,Kanchanaburi,71000.0,w4qzbb4,0,3.568245,0.0,...,1.0,1.0,1.0,NaN,NaN,2.0,NaN,NaN,NaN,NaN
17,35,ก๋วยเตี๋ยวเย็นตาโฟเจ๊หมวย นครสวรรค์,1,False,Nakhon Sawan,60000,w4z1q7n,0,0.000000,0.0,...,1.0,1.0,0.0,NaN,1.0,3.0,NaN,NaN,NaN,NaN
20,38,บะหมี่ ลูกชิ้นปลา,1,False,Bangkok Metropolitan Region,10100,w4rqpk8,0,3.055556,0.0,...,NaN,NaN,NaN,NaN,0.0,2.0,NaN,NaN,NaN,NaN
22,42,ข้าวขาหมู ป้าเพ็ญ,1,False,Bangkok Metropolitan Region,NaN,w4rx0fh,0,5.000000,0.0,...,NaN,NaN,NaN,NaN,NaN,2.0,NaN,NaN,NaN,NaN
23,44,OMG OH MY GELATO,1,False,Bangkok Metropolitan Region,NaN,w4rqytp,0,3.700000,0.0,...,1.0,1.0,0.0,NaN,0.0,0.0,NaN,NaN,NaN,NaN
30,54,Angkor Aran,1,False,Sa Kaeo,10600,w62vv1d,0,0.000000,0.0,...,NaN,NaN,NaN,NaN,1.0,3.0,NaN,1.0,NaN,NaN
33,63,Ajitsukasa Nomura,1,False,Okayama-ken,NaN,wypjpw8,0,4.000000,0.0,...,1.0,1.0,0.0,NaN,0.0,2.0,NaN,NaN,NaN,NaN
36,70,Wrap Master,1,False,Chiang Mai,NaN,w5q6unc,0,3.629630,0.0,...,1.0,1.0,0.0,NaN,NaN,5.0,0.0,0.0,0.0,1.0
37,71,Let's Fry By เมียจ๋า,1,False,Bangkok Metropolitan Region,NaN,w4rqqq0,0,0.000000,0.0,...,1.0,1.0,1.0,NaN,NaN,1.0,NaN,NaN,NaN,NaN
50,96,กัปตันเทเบิลเทอเรส,1,False,Rayong,21160,w60peuj,0,3.000000,0.0,...,NaN,NaN,NaN,NaN,NaN,5.0,NaN,1.0,NaN,NaN
51,97,Nawamin,1,False,Bangkok Metropolitan Region,NaN,w4rwd6w,0,0.000000,0.0,...,NaN,NaN,NaN,NaN,0.0,1.0,NaN,NaN,NaN,NaN
55,102,ยุทธครัวไทย (ป่าไร่เรือนทอง),1,False,Chiang Rai,NaN,w5x1856,0,3.000000,0.0,...,1.0,NaN,1.0,NaN,0.0,3.0,NaN,NaN,NaN,NaN
60,111,เต-ชา ก๋วยเตี๋ยวไข่ไดโนเสาร์,1,False,Chiang Mai,NaN,w5qqhjs,0,3.984000,0.0,...,1.0,1.0,0.0,NaN,1.0,2.0,0.0,0.0,0.0,0.0
61,114,มานีมีนม,1,False,Bangkok Metropolitan Region,10312,w4rw3e0,0,3.793103,18.0,...,NaN,NaN,NaN,NaN,1.0,2.0,NaN,NaN,NaN,1.0
62,116,Zenna Thai And Japanese,1,False,Texas,NaN,9vff298,0,0.000000,0.0,...,1.0,1.0,1.0,NaN,1.0,5.0,NaN,NaN,NaN,NaN
68,125,Oldies Bar & Bistro,1,False,Chon Buri,20230,w4rf8du,0,0.000000,0.0,...,1.0,NaN,1.0,NaN,NaN,2.0,NaN,NaN,NaN,NaN
69,126,Dolce Italia,1,False,Chiang Rai,NaN,w5x18re,0,4.000000,0.0,...,1.0,1.0,0.0,NaN,0.0,1.0,NaN,NaN,NaN,NaN
70,128,ABC Kitchen,1,False,Bangkok Metropolitan Region,10120,w4rw010,0,4.000000,0.0,...,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN
78,146,RJ.GRUNTS Burger&Fries,1,False,Illinois,NaN,dp3wb12,0,4.000000,0.0,...,NaN,NaN,NaN,NaN,1.0,0.0,NaN,NaN,NaN,NaN
81,149,WISH CLINIC,2,False,Khon Kaen,NaN,w6cj7qn,0,5.000000,0.0,...,NaN,NaN,1.0,NaN,1.0,11.0,NaN,NaN,NaN,NaN
82,154,Blue,1,False,Bangkok Metropolitan Region,NaN,w4rmvuv,0,0.000000,0.0,...,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN
86,164,Beta House,1,False,Chon Buri,20130,w4rg88r,0,3.000000,0.0,...,1.0,1.0,NaN,NaN,NaN,2.0,NaN,NaN,NaN,NaN
91,175,ใต้ต้นมะม่วง,1,False,Phuket,83000,w1muz5d,0,3.857143,0.0,...,1.0,1.0,0.0,NaN,0.0,2.0,NaN,NaN,NaN,NaN
93,179,Sabai Thai Massage,2,False,Bangkok Metropolitan Region,NaN,w4rw654,0,3.000000,0.0,...,NaN,NaN,NaN,NaN,NaN,11.0,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
246730,339810,โอ๋โภชนา,1,False,Nakhon Sawan,60110,w4zd285,0,4.000000,0.0,...,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN
246732,339815,ร้านโจ๊กนายฮุย,1,False,Bangkok Metropolitan Region,10700,w4rqq0q,0,0.000000,0.0,...,NaN,NaN,NaN,NaN,0.0,1.0,NaN,NaN,NaN,NaN
246738,339837,ครัวโกดัง,1,False,Kanchanaburi,NaN,w4wbkes,0,3.055556,0.0,...,NaN,NaN,NaN,NaN,NaN,2.0,NaN,NaN,NaN,NaN
246742,339847,New nails,2,False,Bangkok Metropolitan Region,10800,w4rqzfs,0,3.032258,0.0,...,NaN,NaN,NaN,NaN,NaN,11.0,NaN,NaN,NaN,NaN
246757,339876,เจ๊นิจ สาขา 2 ปตท.คูเมือง,1,False,Suphan Buri,72000,w4x4q50,0,4.000000,0.0,...,1.0,1.0,NaN,NaN,NaN,3.0,NaN,NaN,NaN,NaN
246758,339877,Aluco Coffee,1,False,Bangkok Metropolitan Region,NaN,w4rtuss,0,5.000000,0.0,...,1.0,1.0,0.0,NaN,NaN,3.0,NaN,NaN,NaN,NaN
246761,339881,ขนมเข่งทอด เจ๊หงส์,1,False,Phetchaburi,NaN,w4r4d3u,0,0.000000,0.0,...,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN
246762,339882,ส้มตำริมสระหนองบัว,1,False,Surin,NaN,w69senq,0,5.000000,0.0,...,1.0,1.0,1.0,NaN,1.0,2.0,NaN,NaN,NaN,NaN
246764,339885,ครัวสามหนุ่ม,1,False,Bangkok Metropolitan Region,10310,w4rw2wu,0,4.000000,0.0,...,0.0,0.0,0.0,NaN,0.0,3.0,NaN,NaN,NaN,NaN
246770,339895,Café Terrace,1,False,Chon Buri,20110,w4rfdk1,0,0.000000,0.0,...,1.0,NaN,1.0,NaN,1.0,4.0,NaN,1.0,NaN,NaN
246773,339901,Sobok,1,False,Incheon,NaN,wy9vj3n,0,4.500000,0.0,...,NaN,1.0,NaN,NaN,1.0,3.0,NaN,NaN,NaN,NaN
246774,339903,แดงขนมเบื้อง,1,False,Bangkok Metropolitan Region,10600,w4rqngz,0,4.000000,0.0,...,1.0,1.0,0.0,NaN,0.0,0.0,NaN,0.0,NaN,NaN
246775,339904,Pondok Tempo Doeloe,1,False,Bali,80361,qw3ymhg,0,3.000000,0.0,...,1.0,1.0,1.0,NaN,0.0,5.0,NaN,NaN,NaN,NaN
246788,339934,Silla,1,False,Scotland,NaN,gcuvy3z,0,5.000000,0.0,...,NaN,NaN,NaN,NaN,0.0,3.0,NaN,NaN,NaN,NaN
246791,339937,ยู้ ลูกชิ้นปลาเยาวราช,1,False,เขาใหญ่,26000,w4xbz45,0,2.500000,0.0,...,NaN,NaN,NaN,NaN,NaN,3.0,NaN,NaN,NaN,NaN
246792,339938,ลาบชาววัง,1,False,Ubon Ratchathani,NaN,w6dwdkv,0,2.909091,0.0,...,NaN,NaN,NaN,NaN,1.0,3.0,NaN,NaN,NaN,NaN
246793,339939,ส้มตำกันเอง มด&เนะ,1,False,Suphan Buri,72000,w4x4q1j,0,4.000000,0.0,...,NaN,NaN,NaN,NaN,0.0,2.0,NaN,NaN,NaN,NaN
246797,339943,Café in Mind,1,False,Sukhothai,NaN,w5nf99m,1,5.000000,0.0,...,1.0,1.0,0.0,NaN,1.0,2.0,0.0,0.0,0.0,0.0
246801,339953,Best Bar,1,False,Bangkok Metropolitan Region,73170,w4rqd8x,0,3.000000,0.0,...,NaN,NaN,NaN,NaN,NaN,3.0,NaN,NaN,NaN,NaN
246802,339955,Gaa,1,False,Bangkok Metropolitan Region,10330,w4rqpuu,0,4.103250,0.0,...,1.0,NaN,1.0,NaN,NaN,2.0,0.0,0.0,NaN,0.0
246806,339965,เดอนัว ส้มตำ ไก่ย่างเขาสวนกวาง,1,False,Bangkok Metropolitan Region,NaN,w4rmfps,1,0.000000,0.0,...,NaN,NaN,NaN,NaN,NaN,3.0,NaN,NaN,NaN,NaN
246809,339980,Star Hotel Rayong,1,False,Rayong,21000.0,w6200mr,0,0.000000,0.0,...,1.0,1.0,1.0,NaN,1.0,5.0,NaN,1.0,NaN,NaN
246813,339998,TOONGs COFFEE Roasters,1,False,Chiang Mai,50230,w5q6e0g,0,0.000000,0.0,...,1.0,1.0,0.0,NaN,2.0,1.0,NaN,NaN,NaN,NaN
246821,340024,ผู้ชายขายหอย,1,False,Bangkok Metropolitan Region,NaN,w4rwj1f,0,0.000000,0.0,...,1.0,1.0,1.0,NaN,2.0,2.0,NaN,NaN,NaN,NaN
246826,340031,ลาบเขยยอง,1,False,Chiang Mai,NaN,w5q6ws4,0,3.000000,0.0,...,NaN,NaN,NaN,NaN,1.0,4.0,NaN,NaN,NaN,NaN
246827,340035,สำราญโภชนา อตก.,1,False,Bangkok Metropolitan Region,10900.0,w4rw2p8,0,4.483871,0.0,...,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN
246829,340037,Fatboy's Burger Bar,1,False,Kamphaeng Phet,NaN,w4yv8z6,0,4.357143,0.0,...,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN
246836,340054,คนึงหา,1,False,Phatthalung,NaN,w1r5m7j,0,4.000000,0.0,...,1.0,1.0,0.0,NaN,1.0,2.0,NaN,NaN,NaN,NaN
246839,340060,ส้มตำเวียงจันทร์,1,False,Lampang,NaN,w5qb02b,1,3.032258,0.0,...,NaN,NaN,NaN,NaN,0.0,2.0,NaN,NaN,NaN,NaN
246843,340070,สะบายดี คาราโอเกะ,1,False,Bangkok Metropolitan Region,NaN,w4rwjcg,0,0.000000,0.0,...,1.0,NaN,1.0,NaN,NaN,2.0,NaN,NaN,NaN,NaN

# 4. _One-hot-encoder_ for Categorical data

In [ ]:
w_restaurant_df = pandas.get_dummies(w_restaurant_df, columns=['wifi'])

In [ ]:
w_restaurant_df

,id,name,domain_id,closed,city_name,zipcode,geohash,new_open,weighted_average_rating,number_of_chains,...,bookable,best_of_wongnai,number_of_seats,music_venue,hotel_restaurant,pet_friendly,delivery,wifi_0.0,wifi_1.0,wifi_2.0
0,2,นครินทร์ทันตกรรม,2,False,Samut Songkhram,75000,w4rh7g3,0,5.000000,0.0,...,NaN,NaN,13.0,NaN,NaN,NaN,NaN,0,0,0
4,7,Buono Caffe,1,False,Bangkok Metropolitan Region,10220,w4rx4gd,0,3.738462,0.0,...,NaN,NaN,2.0,NaN,NaN,NaN,NaN,0,1,0
5,14,บ้านมุมสบาย,1,False,Chon Buri,NaN,w4rgsyz,0,5.000000,0.0,...,1.0,NaN,5.0,1.0,0.0,0.0,0.0,0,1,0
7,16,Sazanami,1,False,Bangkok Metropolitan Region,10110,w4rw0sp,0,4.130435,0.0,...,NaN,NaN,2.0,NaN,NaN,NaN,NaN,0,0,0
9,21,นกน้ำเต้าหู้,1,False,Narathiwat,96000,w30kt51,0,3.000000,0.0,...,NaN,NaN,2.0,NaN,NaN,NaN,NaN,1,0,0
10,24,Rotee Me Chabu,1,False,Bangkok Metropolitan Region,12130,w4rx3ys,0,4.047619,0.0,...,1.0,NaN,2.0,NaN,NaN,NaN,NaN,1,0,0
11,27,แพอาหารธาราบุรี,1,False,Kanchanaburi,71000.0,w4qzbb4,0,3.568245,0.0,...,1.0,NaN,2.0,NaN,NaN,NaN,NaN,0,0,0
17,35,ก๋วยเตี๋ยวเย็นตาโฟเจ๊หมวย นครสวรรค์,1,False,Nakhon Sawan,60000,w4z1q7n,0,0.000000,0.0,...,0.0,NaN,3.0,NaN,NaN,NaN,NaN,0,1,0
20,38,บะหมี่ ลูกชิ้นปลา,1,False,Bangkok Metropolitan Region,10100,w4rqpk8,0,3.055556,0.0,...,NaN,NaN,2.0,NaN,NaN,NaN,NaN,1,0,0
22,42,ข้าวขาหมู ป้าเพ็ญ,1,False,Bangkok Metropolitan Region,NaN,w4rx0fh,0,5.000000,0.0,...,NaN,NaN,2.0,NaN,NaN,NaN,NaN,0,0,0
23,44,OMG OH MY GELATO,1,False,Bangkok Metropolitan Region,NaN,w4rqytp,0,3.700000,0.0,...,0.0,NaN,0.0,NaN,NaN,NaN,NaN,1,0,0
30,54,Angkor Aran,1,False,Sa Kaeo,10600,w62vv1d,0,0.000000,0.0,...,NaN,NaN,3.0,NaN,1.0,NaN,NaN,0,1,0
33,63,Ajitsukasa Nomura,1,False,Okayama-ken,NaN,wypjpw8,0,4.000000,0.0,...,0.0,NaN,2.0,NaN,NaN,NaN,NaN,1,0,0
36,70,Wrap Master,1,False,Chiang Mai,NaN,w5q6unc,0,3.629630,0.0,...,0.0,NaN,5.0,0.0,0.0,0.0,1.0,0,0,0
37,71,Let's Fry By เมียจ๋า,1,False,Bangkok Metropolitan Region,NaN,w4rqqq0,0,0.000000,0.0,...,1.0,NaN,1.0,NaN,NaN,NaN,NaN,0,0,0
50,96,กัปตันเทเบิลเทอเรส,1,False,Rayong,21160,w60peuj,0,3.000000,0.0,...,NaN,NaN,5.0,NaN,1.0,NaN,NaN,0,0,0
51,97,Nawamin,1,False,Bangkok Metropolitan Region,NaN,w4rwd6w,0,0.000000,0.0,...,NaN,NaN,1.0,NaN,NaN,NaN,NaN,1,0,0
55,102,ยุทธครัวไทย (ป่าไร่เรือนทอง),1,False,Chiang Rai,NaN,w5x1856,0,3.000000,0.0,...,1.0,NaN,3.0,NaN,NaN,NaN,NaN,1,0,0
60,111,เต-ชา ก๋วยเตี๋ยวไข่ไดโนเสาร์,1,False,Chiang Mai,NaN,w5qqhjs,0,3.984000,0.0,...,0.0,NaN,2.0,0.0,0.0,0.0,0.0,0,1,0
61,114,มานีมีนม,1,False,Bangkok Metropolitan Region,10312,w4rw3e0,0,3.793103,18.0,...,NaN,NaN,2.0,NaN,NaN,NaN,1.0,0,1,0
62,116,Zenna Thai And Japanese,1,False,Texas,NaN,9vff298,0,0.000000,0.0,...,1.0,NaN,5.0,NaN,NaN,NaN,NaN,0,1,0
68,125,Oldies Bar & Bistro,1,False,Chon Buri,20230,w4rf8du,0,0.000000,0.0,...,1.0,NaN,2.0,NaN,NaN,NaN,NaN,0,0,0
69,126,Dolce Italia,1,False,Chiang Rai,NaN,w5x18re,0,4.000000,0.0,...,0.0,NaN,1.0,NaN,NaN,NaN,NaN,1,0,0
70,128,ABC Kitchen,1,False,Bangkok Metropolitan Region,10120,w4rw010,0,4.000000,0.0,...,NaN,NaN,0.0,NaN,NaN,NaN,NaN,0,0,0
78,146,RJ.GRUNTS Burger&Fries,1,False,Illinois,NaN,dp3wb12,0,4.000000,0.0,...,NaN,NaN,0.0,NaN,NaN,NaN,NaN,0,1,0
81,149,WISH CLINIC,2,False,Khon Kaen,NaN,w6cj7qn,0,5.000000,0.0,...,1.0,NaN,11.0,NaN,NaN,NaN,NaN,0,1,0
82,154,Blue,1,False,Bangkok Metropolitan Region,NaN,w4rmvuv,0,0.000000,0.0,...,NaN,NaN,1.0,NaN,NaN,NaN,NaN,0,0,0
86,164,Beta House,1,False,Chon Buri,20130,w4rg88r,0,3.000000,0.0,...,NaN,NaN,2.0,NaN,NaN,NaN,NaN,0,0,0
91,175,ใต้ต้นมะม่วง,1,False,Phuket,83000,w1muz5d,0,3.857143,0.0,...,0.0,NaN,2.0,NaN,NaN,NaN,NaN,1,0,0
93,179,Sabai Thai Massage,2,False,Bangkok Metropolitan Region,NaN,w4rw654,0,3.000000,0.0,...,NaN,NaN,11.0,NaN,NaN,NaN,NaN,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
246730,339810,โอ๋โภชนา,1,False,Nakhon Sawan,60110,w4zd285,0,4.000000,0.0,...,NaN,NaN,1.0,NaN,NaN,NaN,NaN,0,0,0
246732,339815,ร้านโจ๊กนายฮุย,1,False,Bangkok Metropolitan Region,10700,w4rqq0q,0,0.000000,0.0,...,NaN,NaN,1.0,NaN,NaN,NaN,NaN,1,0,0
246738,339837,ครัวโกดัง,1,False,Kanchanaburi,NaN,w4wbkes,0,3.055556,0.0,...,NaN,NaN,2.0,NaN,NaN,NaN,NaN,0,0,0
246742,339847,New nails,2,False,Bangkok Metropolitan Region,10800,w4rqzfs,0,3.032258,0.0,...,NaN,NaN,11.0,NaN,NaN,NaN,NaN,0,0,0
246757,339876,เจ๊นิจ สาขา 2 ปตท.คูเมือง,1,False,Suphan Buri,72000,w4x4q50,0,4.000000,0.0,...,NaN,NaN,3.0,NaN,NaN,NaN,NaN,0,0,0
246758,339877,Aluco Coffee,1,False,Bangkok Metropolitan Region,NaN,w4rtuss,0,5.000000,0.0,...,0.0,NaN,3.0,NaN,NaN,NaN,NaN,0,0,0
246761,339881,ขนมเข่งทอด เจ๊หงส์,1,False,Phetchaburi,NaN,w4r4d3u,0,0.000000,0.0,...,NaN,NaN,0.0,NaN,NaN,NaN,NaN,0,0,0
246762,339882,ส้มตำริมสระหนองบัว,1,False,Surin,NaN,w69senq,0,5.000000,0.0,...,1.0,NaN,2.0,NaN,NaN,NaN,NaN,0,1,0
246764,339885,ครัวสามหนุ่ม,1,False,Bangkok Metropolitan Region,10310,w4rw2wu,0,4.000000,0.0,...,0.0,NaN,3.0,NaN,NaN,NaN,NaN,1,0,0
246770,339895,Café Terrace,1,False,Chon Buri,20110,w4rfdk1,0,0.000000,0.0,...,1.0,NaN,4.0,NaN,1.0,NaN,NaN,0,1,0
246773,339901,Sobok,1,False,Incheon,NaN,wy9vj3n,0,4.500000,0.0,...,NaN,NaN,3.0,NaN,NaN,NaN,NaN,0,1,0
246774,339903,แดงขนมเบื้อง,1,False,Bangkok Metropolitan Region,10600,w4rqngz,0,4.000000,0.0,...,0.0,NaN,0.0,NaN,0.0,NaN,NaN,1,0,0
246775,339904,Pondok Tempo Doeloe,1,False,Bali,80361,qw3ymhg,0,3.000000,0.0,...,1.0,NaN,5.0,NaN,NaN,NaN,NaN,1,0,0
246788,339934,Silla,1,False,Scotland,NaN,gcuvy3z,0,5.000000,0.0,...,NaN,NaN,3.0,NaN,NaN,NaN,NaN,1,0,0
246791,339937,ยู้ ลูกชิ้นปลาเยาวราช,1,False,เขาใหญ่,26000,w4xbz45,0,2.500000,0.0,...,NaN,NaN,3.0,NaN,NaN,NaN,NaN,0,0,0
246792,339938,ลาบชาววัง,1,False,Ubon Ratchathani,NaN,w6dwdkv,0,2.909091,0.0,...,NaN,NaN,3.0,NaN,NaN,NaN,NaN,0,1,0
246793,339939,ส้มตำกันเอง มด&เนะ,1,False,Suphan Buri,72000,w4x4q1j,0,4.000000,0.0,...,NaN,NaN,2.0,NaN,NaN,NaN,NaN,1,0,0
246797,339943,Café in Mind,1,False,Sukhothai,NaN,w5nf99m,1,5.000000,0.0,...,0.0,NaN,2.0,0.0,0.0,0.0,0.0,0,1,0
246801,339953,Best Bar,1,False,Bangkok Metropolitan Region,73170,w4rqd8x,0,3.000000,0.0,...,NaN,NaN,3.0,NaN,NaN,NaN,NaN,0,0,0
246802,339955,Gaa,1,False,Bangkok Metropolitan Region,10330,w4rqpuu,0,4.103250,0.0,...,1.0,NaN,2.0,0.0,0.0,NaN,0.0,0,0,0
246806,339965,เดอนัว ส้มตำ ไก่ย่างเขาสวนกวาง,1,False,Bangkok Metropolitan Region,NaN,w4rmfps,1,0.000000,0.0,...,NaN,NaN,3.0,NaN,NaN,NaN,NaN,0,0,0
246809,339980,Star Hotel Rayong,1,False,Rayong,21000.0,w6200mr,0,0.000000,0.0,...,1.0,NaN,5.0,NaN,1.0,NaN,NaN,0,1,0
246813,339998,TOONGs COFFEE Roasters,1,False,Chiang Mai,50230,w5q6e0g,0,0.000000,0.0,...,0.0,NaN,1.0,NaN,NaN,NaN,NaN,0,0,1
246821,340024,ผู้ชายขายหอย,1,False,Bangkok Metropolitan Region,NaN,w4rwj1f,0,0.000000,0.0,...,1.0,NaN,2.0,NaN,NaN,NaN,NaN,0,0,1
246826,340031,ลาบเขยยอง,1,False,Chiang Mai,NaN,w5q6ws4,0,3.000000,0.0,...,NaN,NaN,4.0,NaN,NaN,NaN,NaN,0,1,0
246827,340035,สำราญโภชนา อตก.,1,False,Bangkok Metropolitan Region,10900.0,w4rw2p8,0,4.483871,0.0,...,NaN,NaN,1.0,NaN,NaN,NaN,NaN,0,0,0
246829,340037,Fatboy's Burger Bar,1,False,Kamphaeng Phet,NaN,w4yv8z6,0,4.357143,0.0,...,NaN,NaN,1.0,NaN,NaN,NaN,NaN,0,0,0
246836,340054,คนึงหา,1,False,Phatthalung,NaN,w1r5m7j,0,4.000000,0.0,...,0.0,NaN,2.0,NaN,NaN,NaN,NaN,0,1,0
246839,340060,ส้มตำเวียงจันทร์,1,False,Lampang,NaN,w5qb02b,1,3.032258,0.0,...,NaN,NaN,2.0,NaN,NaN,NaN,NaN,1,0,0
246843,340070,สะบายดี คาราโอเกะ,1,False,Bangkok Metropolitan Region,NaN,w4rwjcg,0,0.000000,0.0,...,1.0,NaN,2.0,NaN,NaN,NaN,NaN,0,0,0

# 5. _select_ data within a _range_
http://pandas.pydata.org/pandas-docs/stable/generated/pandas.Series.between.html

In [ ]:
new_df = w_restaurant_df['weighted_average_rating'].between(4, 5, inclusive=True)

In [ ]:
new_df

0          True
4         False
5          True
7          True
9         False
10         True
11        False
17        False
20        False
22         True
23        False
30        False
33         True
36        False
37        False
50        False
51        False
55        False
60        False
61        False
62        False
68        False
69         True
70         True
78         True
81         True
82        False
86        False
91        False
93        False
          ...
246730     True
246732    False
246738    False
246742    False
246757     True
246758     True
246761    False
246762     True
246764     True
246770    False
246773     True
246774     True
246775    False
246788     True
246791    False
246792    False
246793     True
246797     True
246801    False
246802     True
246806    False
246809    False
246813    False
246821    False
246826    False
246827     True
246829     True
246836     True
246839    False
246843    False
Name: weighted_average_rating, dtype: bool

In [ ]:
w_restaurant_df[new_df]

,id,name,domain_id,closed,city_name,zipcode,geohash,new_open,weighted_average_rating,number_of_chains,...,bookable,best_of_wongnai,number_of_seats,music_venue,hotel_restaurant,pet_friendly,delivery,wifi_0.0,wifi_1.0,wifi_2.0
0,2,นครินทร์ทันตกรรม,2,False,Samut Songkhram,75000,w4rh7g3,0,5.000000,0.0,...,NaN,NaN,13.0,NaN,NaN,NaN,NaN,0,0,0
5,14,บ้านมุมสบาย,1,False,Chon Buri,NaN,w4rgsyz,0,5.000000,0.0,...,1.0,NaN,5.0,1.0,0.0,0.0,0.0,0,1,0
7,16,Sazanami,1,False,Bangkok Metropolitan Region,10110,w4rw0sp,0,4.130435,0.0,...,NaN,NaN,2.0,NaN,NaN,NaN,NaN,0,0,0
10,24,Rotee Me Chabu,1,False,Bangkok Metropolitan Region,12130,w4rx3ys,0,4.047619,0.0,...,1.0,NaN,2.0,NaN,NaN,NaN,NaN,1,0,0
22,42,ข้าวขาหมู ป้าเพ็ญ,1,False,Bangkok Metropolitan Region,NaN,w4rx0fh,0,5.000000,0.0,...,NaN,NaN,2.0,NaN,NaN,NaN,NaN,0,0,0
33,63,Ajitsukasa Nomura,1,False,Okayama-ken,NaN,wypjpw8,0,4.000000,0.0,...,0.0,NaN,2.0,NaN,NaN,NaN,NaN,1,0,0
69,126,Dolce Italia,1,False,Chiang Rai,NaN,w5x18re,0,4.000000,0.0,...,0.0,NaN,1.0,NaN,NaN,NaN,NaN,1,0,0
70,128,ABC Kitchen,1,False,Bangkok Metropolitan Region,10120,w4rw010,0,4.000000,0.0,...,NaN,NaN,0.0,NaN,NaN,NaN,NaN,0,0,0
78,146,RJ.GRUNTS Burger&Fries,1,False,Illinois,NaN,dp3wb12,0,4.000000,0.0,...,NaN,NaN,0.0,NaN,NaN,NaN,NaN,0,1,0
81,149,WISH CLINIC,2,False,Khon Kaen,NaN,w6cj7qn,0,5.000000,0.0,...,1.0,NaN,11.0,NaN,NaN,NaN,NaN,0,1,0
100,198,กาแฟชะมด,1,False,Chiang Mai,50210,w5q7jev,0,5.000000,0.0,...,NaN,NaN,1.0,NaN,NaN,NaN,NaN,0,0,0
102,203,Fuji Japanese Restaurant,1,False,Nakhon Sawan,60000,w4z1q6e,0,4.368421,0.0,...,NaN,NaN,3.0,NaN,NaN,NaN,NaN,0,0,0
103,204,Kau Kee,1,False,New Territories,NaN,wecnv8e,0,4.597403,0.0,...,1.0,NaN,2.0,NaN,NaN,NaN,NaN,1,0,0
147,342,อิ่มอร่อย,1,False,Chon Buri,NaN,w4rb06k,1,5.000000,0.0,...,NaN,NaN,2.0,NaN,NaN,NaN,NaN,0,1,0
153,351,ขาหมู คุณแน็ค,1,False,Chiang Mai,NaN,w5q6ujg,0,4.000000,0.0,...,NaN,NaN,2.0,NaN,NaN,NaN,1.0,0,1,0
155,356,ก๋ง คอฟฟี่,1,False,Bangkok Metropolitan Region,NaN,w4x812s,0,4.000000,0.0,...,NaN,NaN,1.0,NaN,NaN,NaN,NaN,1,0,0
158,361,ก่วยเตี๋ยวลูกชิ้นหมูน้ำใสศรีสยาม,1,False,Bangkok Metropolitan Region,10140,w4rmycy,0,5.000000,0.0,...,NaN,NaN,2.0,NaN,NaN,NaN,NaN,1,0,0
188,420,COFFEE A DAY,1,False,Krabi,NaN,w1qhp8w,0,4.000000,26.0,...,NaN,NaN,2.0,NaN,1.0,0.0,NaN,0,1,0
203,444,The witch t cafe,1,False,Loei,42000,w707dz5,0,4.000000,0.0,...,1.0,NaN,3.0,NaN,NaN,NaN,NaN,0,1,0
224,472,บ้านสีม่วง,1,False,Bangkok Metropolitan Region,NaN,w4rw6kn,1,5.000000,0.0,...,1.0,NaN,3.0,1.0,NaN,NaN,NaN,0,1,0
230,478,หวานละมุน-ของหวานไทย,1,False,Chiang Rai,NaN,w5x187v,0,5.000000,0.0,...,NaN,NaN,2.0,NaN,NaN,NaN,NaN,0,0,0
247,509,Masterpiece clinic,2,False,Bangkok Metropolitan Region,10330,w4rqpwk,0,4.674938,0.0,...,NaN,NaN,11.0,NaN,NaN,NaN,NaN,0,0,0
262,536,เนื้อตุ๋นบูรพา By ข่าแก่,1,False,Chon Buri,NaN,w4rg8fb,1,5.000000,0.0,...,NaN,NaN,2.0,NaN,NaN,NaN,NaN,1,0,0
281,565,Cooking mama,1,False,Bangkok Metropolitan Region,74000.0,w4rm1gt,0,5.000000,0.0,...,1.0,NaN,2.0,NaN,NaN,NaN,NaN,0,1,0
284,571,ชุนเปี๊ยะ,1,False,Suphan Buri,NaN,w4x0q63,0,5.000000,0.0,...,1.0,NaN,0.0,NaN,NaN,NaN,NaN,0,0,0
292,582,สนามเด็กเล่น,1,False,Bangkok Metropolitan Region,12000,w4rx2tn,0,4.000000,0.0,...,1.0,NaN,2.0,NaN,NaN,NaN,NaN,0,1,0
318,615,เนื้อตุ๋นหน้าโรงรับจำนำไทยฮั่งล้ง พระราม 4,1,False,Bangkok Metropolitan Region,10110,w4rw037,0,5.000000,0.0,...,NaN,NaN,1.0,NaN,NaN,NaN,NaN,1,0,0
334,635,Big John Seafood Restuarant,1,False,Surat Thani,84140,w1xn40c,0,4.000000,0.0,...,1.0,NaN,3.0,NaN,NaN,NaN,NaN,0,1,0
351,652,ชายสี่บะหมี่เกี๊ยว,1,False,Bangkok Metropolitan Region,NaN,w4rm1fq,0,5.000000,0.0,...,NaN,NaN,2.0,NaN,NaN,NaN,NaN,0,0,0
371,680,ก๋วยเตี๋ยวเนื้อตุ๋น•เอ็นตุ๋นยาจีน,1,False,Bangkok Metropolitan Region,NaN,w4rtc2g,0,4.043478,0.0,...,NaN,NaN,2.0,NaN,NaN,NaN,NaN,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
246626,339647,Indigo Cafe & Restaurant,1,False,Bangkok Metropolitan Region,10240,w4rw3gn,0,4.142322,0.0,...,NaN,NaN,4.0,NaN,NaN,NaN,NaN,0,1,0
246633,339654,ทรัพย์รุ่งเรือง ขนมไทย,1,False,Bangkok Metropolitan Region,73170,w4rqfp7,0,5.000000,0.0,...,NaN,NaN,0.0,NaN,NaN,NaN,NaN,0,0,0
246635,339656,ข้าวซอยแม่พิน,1,False,Chiang Rai,57000,w5wcr85,0,4.058824,0.0,...,NaN,NaN,2.0,NaN,NaN,NaN,NaN,0,1,0
246655,339680,ซุปเด็ดก๋วยเตี๋ยวหมู,1,False,Chiang Rai,NaN,w5wcpzb,0,5.000000,0.0,...,NaN,NaN,1.0,NaN,NaN,NaN,NaN,1,0,0
246660,339686,หมี่น้ำกุ้ง,1,False,Phuket,83000.0,w1muycu,0,4.000000,0.0,...,0.0,NaN,2.0,NaN,NaN,NaN,NaN,1,0,0
246661,339687,Twiz ทวิส,1,False,Bangkok Metropolitan Region,NaN,w4rqp64,0,4.000000,0.0,...,NaN,NaN,0.0,NaN,NaN,NaN,NaN,0,0,0
246662,339688,ฮ้งไอศกรีม,1,False,Phitsanulok,NaN,w4zpq4n,0,4.411765,0.0,...,NaN,NaN,2.0,NaN,NaN,NaN,NaN,0,0,0
246670,339697,ก๋วยเตี๋ยวขลุกขลิก,1,False,Chanthaburi,22120,w60xc4p,0,4.222222,0.0,...,0.0,NaN,1.0,NaN,NaN,NaN,NaN,1,0,0
246679,339711,NaJu (นาจู) 나주,1,False,Nakhon Ratchasima,NaN,w68t5qb,0,4.769231,0.0,...,NaN,NaN,2.0,NaN,NaN,NaN,NaN,0,0,1
246690,339727,All Season Cafe' The Espresso Bar,1,False,Rayong,21140,w4rcyzw,0,4.000000,0.0,...,1.0,NaN,2.0,NaN,NaN,NaN,NaN,0,1,0
246691,339730,DOZO SHABU SUKI,1,False,Chon Buri,NaN,w4ru7f1,0,5.000000,0.0,...,1.0,NaN,2.0,NaN,NaN,NaN,NaN,0,1,0
246692,339731,รสเลิศ ก๋วยเตี๋ยวหมูตุ๋น เกาเหลาไข่ต้ม,1,False,Chon Buri,NaN,w4rfbg0,0,5.000000,0.0,...,1.0,NaN,2.0,NaN,NaN,NaN,NaN,0,0,0
246696,339740,ring the bell homemade cafe,1,False,Bangkok Metropolitan Region,NaN,w4rw51s,0,4.444444,0.0,...,NaN,NaN,2.0,NaN,NaN,NaN,NaN,0,0,1
246703,339749,เตี๋ยวเรือต่อชามตาก,1,True,Tak,NaN,w5n2p95,0,4.000000,0.0,...,NaN,NaN,2.0,NaN,NaN,NaN,NaN,0,0,0
246710,339767,ซ้อลี่ บะหมี่หมู,1,False,Bangkok Metropolitan Region,NaN,w4rnsvn,0,4.000000,0.0,...,NaN,NaN,2.0,NaN,NaN,NaN,NaN,0,0,0
246719,339783,ปิ้งย่างหม่าล่า เด้าลิ้น รวมโชคมอล,1,False,Chiang Mai,NaN,w5q7j4b,1,5.000000,0.0,...,0.0,NaN,1.0,NaN,NaN,NaN,NaN,1,0,0
246730,339810,โอ๋โภชนา,1,False,Nakhon Sawan,60110,w4zd285,0,4.000000,0.0,...,NaN,NaN,1.0,NaN,NaN,NaN,NaN,0,0,0
246757,339876,เจ๊นิจ สาขา 2 ปตท.คูเมือง,1,False,Suphan Buri,72000,w4x4q50,0,4.000000,0.0,...,NaN,NaN,3.0,NaN,NaN,NaN,NaN,0,0,0
246758,339877,Aluco Coffee,1,False,Bangkok Metropolitan Region,NaN,w4rtuss,0,5.000000,0.0,...,0.0,NaN,3.0,NaN,NaN,NaN,NaN,0,0,0
246762,339882,ส้มตำริมสระหนองบัว,1,False,Surin,NaN,w69senq,0,5.000000,0.0,...,1.0,NaN,2.0,NaN,NaN,NaN,NaN,0,1,0
246764,339885,ครัวสามหนุ่ม,1,False,Bangkok Metropolitan Region,10310,w4rw2wu,0,4.000000,0.0,...,0.0,NaN,3.0,NaN,NaN,NaN,NaN,1,0,0
246773,339901,Sobok,1,False,Incheon,NaN,wy9vj3n,0,4.500000,0.0,...,NaN,NaN,3.0,NaN,NaN,NaN,NaN,0,1,0
246774,339903,แดงขนมเบื้อง,1,False,Bangkok Metropolitan Region,10600,w4rqngz,0,4.000000,0.0,...,0.0,NaN,0.0,NaN,0.0,NaN,NaN,1,0,0
246788,339934,Silla,1,False,Scotland,NaN,gcuvy3z,0,5.000000,0.0,...,NaN,NaN,3.0,NaN,NaN,NaN,NaN,1,0,0
246793,339939,ส้มตำกันเอง มด&เนะ,1,False,Suphan Buri,72000,w4x4q1j,0,4.000000,0.0,...,NaN,NaN,2.0,NaN,NaN,NaN,NaN,1,0,0
246797,339943,Café in Mind,1,False,Sukhothai,NaN,w5nf99m,1,5.000000,0.0,...,0.0,NaN,2.0,0.0,0.0,0.0,0.0,0,1,0
246802,339955,Gaa,1,False,Bangkok Metropolitan Region,10330,w4rqpuu,0,4.103250,0.0,...,1.0,NaN,2.0,0.0,0.0,NaN,0.0,0,0,0
246827,340035,สำราญโภชนา อตก.,1,False,Bangkok Metropolitan Region,10900.0,w4rw2p8,0,4.483871,0.0,...,NaN,NaN,1.0,NaN,NaN,NaN,NaN,0,0,0
246829,340037,Fatboy's Burger Bar,1,False,Kamphaeng Phet,NaN,w4yv8z6,0,4.357143,0.0,...,NaN,NaN,1.0,NaN,NaN,NaN,NaN,0,0,0
246836,340054,คนึงหา,1,False,Phatthalung,NaN,w1r5m7j,0,4.000000,0.0,...,0.0,NaN,2.0,NaN,NaN,NaN,NaN,0,1,0

# 6. View only some columns

In [ ]:
w_restaurant_df[['id','name','price_range','weighted_average_rating']]

,id,name,price_range,weighted_average_rating
0,2,นครินทร์ทันตกรรม,NaN,5.000000
4,7,Buono Caffe,1.0,3.738462
5,14,บ้านมุมสบาย,3.0,5.000000
7,16,Sazanami,4.0,4.130435
9,21,นกน้ำเต้าหู้,1.0,3.000000
10,24,Rotee Me Chabu,2.0,4.047619
11,27,แพอาหารธาราบุรี,3.0,3.568245
17,35,ก๋วยเตี๋ยวเย็นตาโฟเจ๊หมวย นครสวรรค์,1.0,0.000000
20,38,บะหมี่ ลูกชิ้นปลา,1.0,3.055556
22,42,ข้าวขาหมู ป้าเพ็ญ,1.0,5.000000
23,44,OMG OH MY GELATO,1.0,3.700000
30,54,Angkor Aran,1.0,0.000000
33,63,Ajitsukasa Nomura,3.0,4.000000
36,70,Wrap Master,1.0,3.629630
37,71,Let's Fry By เมียจ๋า,2.0,0.000000
50,96,กัปตันเทเบิลเทอเรส,4.0,3.000000
51,97,Nawamin,1.0,0.000000
55,102,ยุทธครัวไทย (ป่าไร่เรือนทอง),1.0,3.000000
60,111,เต-ชา ก๋วยเตี๋ยวไข่ไดโนเสาร์,1.0,3.984000
61,114,มานีมีนม,2.0,3.793103
62,116,Zenna Thai And Japanese,3.0,0.000000
68,125,Oldies Bar & Bistro,1.0,0.000000
69,126,Dolce Italia,1.0,4.000000
70,128,ABC Kitchen,2.0,4.000000
78,146,RJ.GRUNTS Burger&Fries,4.0,4.000000
81,149,WISH CLINIC,NaN,5.000000
82,154,Blue,1.0,0.000000
86,164,Beta House,2.0,3.000000
91,175,ใต้ต้นมะม่วง,1.0,3.857143
93,179,Sabai Thai Massage,NaN,3.000000
...,...,...,...,...
246730,339810,โอ๋โภชนา,1.0,4.000000
246732,339815,ร้านโจ๊กนายฮุย,1.0,0.000000
246738,339837,ครัวโกดัง,1.0,3.055556
246742,339847,New nails,NaN,3.032258
246757,339876,เจ๊นิจ สาขา 2 ปตท.คูเมือง,1.0,4.000000
246758,339877,Aluco Coffee,1.0,5.000000
246761,339881,ขนมเข่งทอด เจ๊หงส์,1.0,0.000000
246762,339882,ส้มตำริมสระหนองบัว,1.0,5.000000
246764,339885,ครัวสามหนุ่ม,2.0,4.000000
246770,339895,Café Terrace,2.0,0.000000
246773,339901,Sobok,2.0,4.500000
246774,339903,แดงขนมเบื้อง,1.0,4.000000
246775,339904,Pondok Tempo Doeloe,4.0,3.000000
246788,339934,Silla,4.0,5.000000
246791,339937,ยู้ ลูกชิ้นปลาเยาวราช,1.0,2.500000
246792,339938,ลาบชาววัง,2.0,2.909091
246793,339939,ส้มตำกันเอง มด&เนะ,1.0,4.000000
246797,339943,Café in Mind,1.0,5.000000
246801,339953,Best Bar,2.0,3.000000
246802,339955,Gaa,5.0,4.103250
246806,339965,เดอนัว ส้มตำ ไก่ย่างเขาสวนกวาง,2.0,0.000000
246809,339980,Star Hotel Rayong,NaN,0.000000
246813,339998,TOONGs COFFEE Roasters,1.0,0.000000
246821,340024,ผู้ชายขายหอย,2.0,0.000000
246826,340031,ลาบเขยยอง,2.0,3.000000
246827,340035,สำราญโภชนา อตก.,1.0,4.483871
246829,340037,Fatboy's Burger Bar,2.0,4.357143
246836,340054,คนึงหา,2.0,4.000000
246839,340060,ส้มตำเวียงจันทร์,1.0,3.032258
246843,340070,สะบายดี คาราโอเกะ,1.0,0.000000

In [ ]:
w_restaurant_df[new_df][['id','name','price_range','weighted_average_rating']]

,id,name,price_range,weighted_average_rating
0,2,นครินทร์ทันตกรรม,NaN,5.000000
5,14,บ้านมุมสบาย,3.0,5.000000
7,16,Sazanami,4.0,4.130435
10,24,Rotee Me Chabu,2.0,4.047619
22,42,ข้าวขาหมู ป้าเพ็ญ,1.0,5.000000
33,63,Ajitsukasa Nomura,3.0,4.000000
69,126,Dolce Italia,1.0,4.000000
70,128,ABC Kitchen,2.0,4.000000
78,146,RJ.GRUNTS Burger&Fries,4.0,4.000000
81,149,WISH CLINIC,NaN,5.000000
100,198,กาแฟชะมด,2.0,5.000000
102,203,Fuji Japanese Restaurant,3.0,4.368421
103,204,Kau Kee,2.0,4.597403
147,342,อิ่มอร่อย,1.0,5.000000
153,351,ขาหมู คุณแน็ค,1.0,4.000000
155,356,ก๋ง คอฟฟี่,1.0,4.000000
158,361,ก่วยเตี๋ยวลูกชิ้นหมูน้ำใสศรีสยาม,1.0,5.000000
188,420,COFFEE A DAY,1.0,4.000000
203,444,The witch t cafe,1.0,4.000000
224,472,บ้านสีม่วง,1.0,5.000000
230,478,หวานละมุน-ของหวานไทย,1.0,5.000000
247,509,Masterpiece clinic,NaN,4.674938
262,536,เนื้อตุ๋นบูรพา By ข่าแก่,1.0,5.000000
281,565,Cooking mama,1.0,5.000000
284,571,ชุนเปี๊ยะ,1.0,5.000000
292,582,สนามเด็กเล่น,2.0,4.000000
318,615,เนื้อตุ๋นหน้าโรงรับจำนำไทยฮั่งล้ง พระราม 4,1.0,5.000000
334,635,Big John Seafood Restuarant,2.0,4.000000
351,652,ชายสี่บะหมี่เกี๊ยว,1.0,5.000000
371,680,ก๋วยเตี๋ยวเนื้อตุ๋น•เอ็นตุ๋นยาจีน,1.0,4.043478
...,...,...,...,...
246626,339647,Indigo Cafe & Restaurant,3.0,4.142322
246633,339654,ทรัพย์รุ่งเรือง ขนมไทย,1.0,5.000000
246635,339656,ข้าวซอยแม่พิน,1.0,4.058824
246655,339680,ซุปเด็ดก๋วยเตี๋ยวหมู,1.0,5.000000
246660,339686,หมี่น้ำกุ้ง,1.0,4.000000
246661,339687,Twiz ทวิส,1.0,4.000000
246662,339688,ฮ้งไอศกรีม,1.0,4.411765
246670,339697,ก๋วยเตี๋ยวขลุกขลิก,1.0,4.222222
246679,339711,NaJu (นาจู) 나주,3.0,4.769231
246690,339727,All Season Cafe' The Espresso Bar,2.0,4.000000
246691,339730,DOZO SHABU SUKI,2.0,5.000000
246692,339731,รสเลิศ ก๋วยเตี๋ยวหมูตุ๋น เกาเหลาไข่ต้ม,1.0,5.000000
246696,339740,ring the bell homemade cafe,1.0,4.444444
246703,339749,เตี๋ยวเรือต่อชามตาก,1.0,4.000000
246710,339767,ซ้อลี่ บะหมี่หมู,1.0,4.000000
246719,339783,ปิ้งย่างหม่าล่า เด้าลิ้น รวมโชคมอล,1.0,5.000000
246730,339810,โอ๋โภชนา,1.0,4.000000
246757,339876,เจ๊นิจ สาขา 2 ปตท.คูเมือง,1.0,4.000000
246758,339877,Aluco Coffee,1.0,5.000000
246762,339882,ส้มตำริมสระหนองบัว,1.0,5.000000
246764,339885,ครัวสามหนุ่ม,2.0,4.000000
246773,339901,Sobok,2.0,4.500000
246774,339903,แดงขนมเบื้อง,1.0,4.000000
246788,339934,Silla,4.0,5.000000
246793,339939,ส้มตำกันเอง มด&เนะ,1.0,4.000000
246797,339943,Café in Mind,1.0,5.000000
246802,339955,Gaa,5.0,4.103250
246827,340035,สำราญโภชนา อตก.,1.0,4.483871
246829,340037,Fatboy's Burger Bar,2.0,4.357143
246836,340054,คนึงหา,2.0,4.000000

# 7. Select only records with a specific value

In [ ]:
selected_record = w_restaurant_df['domain_id']==4

In [ ]:
selected_record = w_restaurant_df['domain_id']>=4 && w_restaurant_df['domain_id']<5

In [ ]:
w_restaurant_df[selected_record]

,id,name,domain_id,closed,city_name,zipcode,geohash,new_open,weighted_average_rating,number_of_chains,...,bookable,best_of_wongnai,number_of_seats,music_venue,hotel_restaurant,pet_friendly,delivery,wifi_0.0,wifi_1.0,wifi_2.0
40987,74402,ตลาดอยู่ดินกินดี,4,False,Chon Buri,NaN,w4rb8y4,0,3.000000,0.0,...,NaN,NaN,5.0,NaN,NaN,NaN,NaN,0,0,0
59766,99118,สุจินต์หมูยอ,4,False,Chiang Rai,57000,w5wcpxy,0,4.118919,0.0,...,1.0,NaN,0.0,NaN,NaN,NaN,NaN,1,0,0
80088,125063,Zanook wake park,4,False,Bangkok Metropolitan Region,NaN,w4rmsq9,0,4.500000,0.0,...,NaN,NaN,2.0,NaN,NaN,NaN,NaN,0,0,0
80260,125303,Urban Playground Climbing,4,False,Bangkok Metropolitan Region,10110,w4rw0ss,0,5.000000,0.0,...,NaN,NaN,13.0,NaN,NaN,NaN,NaN,0,0,0
110557,165352,ตลาดนัดม.เกษตร ศรีราชา,4,False,Chon Buri,20230,w4rf8kx,0,5.000000,0.0,...,0.0,NaN,0.0,NaN,NaN,NaN,NaN,0,0,0
157008,225624,Craftfeteria,4,False,Bangkok Metropolitan Region,NaN,w4rqpy6,0,4.500000,0.0,...,NaN,NaN,11.0,NaN,NaN,NaN,NaN,0,0,0
169183,241300,ทุ่งดอกเก๊กฮวย บ้านอมลอง,4,False,Chiang Mai,NaN,w5q5euc,0,4.000000,0.0,...,0.0,NaN,0.0,0.0,0.0,0.0,0.0,1,0,0
188885,265935,เพลินฤดี ไนท์ มาร์เก็ต,4,False,Chiang Mai,50100,w5q6uu4,0,4.036585,0.0,...,NaN,NaN,5.0,1.0,NaN,NaN,NaN,1,0,0
224582,310065,Cook's Step โรงเรียนสอนทำอาหาร,4,False,Bangkok Metropolitan Region,NaN,w4rtdrn,0,0.000000,0.0,...,1.0,NaN,2.0,NaN,NaN,NaN,1.0,0,0,1

In [ ]:
selected_record = w_restaurant_df['domain_id'] != 1

In [ ]:
w_restaurant_df[selected_record]

,id,name,domain_id,closed,city_name,zipcode,geohash,new_open,weighted_average_rating,number_of_chains,...,bookable,best_of_wongnai,number_of_seats,music_venue,hotel_restaurant,pet_friendly,delivery,wifi_0.0,wifi_1.0,wifi_2.0
0,2,นครินทร์ทันตกรรม,2,False,Samut Songkhram,75000,w4rh7g3,0,5.000000,0.0,...,NaN,NaN,13.0,NaN,NaN,NaN,NaN,0,0,0
81,149,WISH CLINIC,2,False,Khon Kaen,NaN,w6cj7qn,0,5.000000,0.0,...,1.0,NaN,11.0,NaN,NaN,NaN,NaN,0,1,0
93,179,Sabai Thai Massage,2,False,Bangkok Metropolitan Region,NaN,w4rw654,0,3.000000,0.0,...,NaN,NaN,11.0,NaN,NaN,NaN,NaN,0,0,0
167,374,Saloon of Barber,2,False,Bangkok Metropolitan Region,10110,w4rw0be,1,0.000000,0.0,...,NaN,NaN,11.0,NaN,NaN,NaN,NaN,0,0,0
247,509,Masterpiece clinic,2,False,Bangkok Metropolitan Region,10330,w4rqpwk,0,4.674938,0.0,...,NaN,NaN,11.0,NaN,NaN,NaN,NaN,0,0,0
319,616,Chaba Nails & Eyelashes Pro,2,False,Bangkok Metropolitan Region,NaN,w4rw98b,0,3.120000,6.0,...,1.0,NaN,11.0,NaN,NaN,NaN,NaN,0,0,0
374,684,นิ้วนาง NAIL & 3D EYEBROW,2,False,Bangkok Metropolitan Region,73170,w4rq7p0,0,5.000000,0.0,...,1.0,NaN,11.0,NaN,NaN,NaN,NaN,0,1,0
426,763,Lady Tandy สักคิ้ว 3 มิติ,2,False,สงขลา,90000,w1r8cjw,0,5.000000,0.0,...,NaN,NaN,11.0,NaN,NaN,NaN,NaN,0,0,0
469,831,สักคิ้วเสริมโหงวเฮ้ง ช่างติ้ง,2,False,Sakon Nakhon,NaN,w7417zy,0,5.000000,0.0,...,NaN,NaN,11.0,NaN,NaN,NaN,NaN,0,1,0
512,883,Nail & Beauty Bars,2,False,Bangkok Metropolitan Region,NaN,w4rmv1n,0,5.000000,0.0,...,NaN,NaN,11.0,NaN,NaN,NaN,NaN,0,0,0
530,903,บ้านนวด มนชยา,2,False,Bangkok Metropolitan Region,10230,w4rwdxu,0,5.000000,0.0,...,NaN,NaN,12.0,NaN,NaN,NaN,NaN,0,0,0
610,1008,น้ำฝนเมจิกแฮร์,2,False,Phuket,83000,w1muwwt,0,5.000000,0.0,...,NaN,NaN,12.0,NaN,NaN,NaN,NaN,0,0,0
642,1057,PopHairStylist,2,False,Bangkok Metropolitan Region,NaN,w4rqjs9,0,5.000000,0.0,...,NaN,NaN,11.0,NaN,NaN,NaN,NaN,0,0,0
732,1199,Thai Herb Spa,2,False,Chiang Mai,NaN,w5q674y,0,0.000000,0.0,...,NaN,NaN,13.0,NaN,NaN,NaN,NaN,0,1,0
765,1254,Venus clinic,2,False,Bangkok Metropolitan Region,NaN,w4rw383,0,0.000000,0.0,...,NaN,NaN,12.0,NaN,NaN,NaN,NaN,0,0,0
791,1288,sassy nail plus,2,False,Bangkok Metropolitan Region,10210,w4rwbj6,0,4.000000,0.0,...,NaN,NaN,11.0,NaN,NaN,NaN,NaN,0,0,0
899,1431,หัตถพรนวดแผนไทย & สปา,2,False,Bangkok Metropolitan Region,10170,w4rqmyq,0,0.000000,0.0,...,NaN,NaN,11.0,NaN,NaN,NaN,NaN,0,0,0
906,1439,Dhoom Hair,2,False,Bangkok Metropolitan Region,NaN,w4rwcuw,0,5.000000,0.0,...,1.0,NaN,12.0,NaN,NaN,NaN,NaN,0,0,1
1329,2185,ปัณฑา เดย์ สปา,2,False,Bangkok Metropolitan Region,NaN,w4rw7d3,0,0.000000,0.0,...,NaN,NaN,12.0,NaN,NaN,NaN,NaN,0,0,0
1402,2313,Mentor Gym,2,False,Bangkok Metropolitan Region,NaN,w4rqxm0,0,0.000000,0.0,...,NaN,NaN,14.0,NaN,NaN,NaN,NaN,0,0,0
1428,2369,เสริมสวย ต้นอ้อบิวตี้ แฮร์สปา,2,False,Kalasin,NaN,w6ct7ms,0,5.000000,0.0,...,1.0,NaN,11.0,NaN,NaN,NaN,NaN,0,1,0
1494,2507,Ladyford Hair Studio,2,False,Bangkok Metropolitan Region,NaN,w4rqpvg,1,5.000000,0.0,...,1.0,NaN,11.0,NaN,NaN,NaN,NaN,0,0,0
1509,2536,ร้อยพันจันทร์นวดแผนไทย,2,False,Chiang Mai,NaN,w5q6dfj,0,0.000000,0.0,...,NaN,NaN,13.0,NaN,NaN,NaN,NaN,0,0,0
1577,2652,บ้านเตยหอมสปา by คุณทราย,2,False,Bangkok Metropolitan Region,10110,w4rmqfg,0,5.000000,0.0,...,NaN,NaN,11.0,NaN,NaN,NaN,NaN,0,1,0
1665,2791,Sexy Wax,2,False,Bangkok Metropolitan Region,10700,w4rqq85,0,5.000000,0.0,...,1.0,NaN,13.0,NaN,NaN,NaN,NaN,0,0,0
1682,2813,พี่ดาว ตลาดนกฮูก,2,False,Bangkok Metropolitan Region,NaN,w4rqyu9,1,3.903226,0.0,...,NaN,NaN,11.0,NaN,NaN,NaN,NaN,0,0,0
1740,2945,Noina nail art,2,False,Si Sa Ket,33000,w6djyr8,0,0.000000,0.0,...,NaN,NaN,12.0,NaN,NaN,NaN,NaN,0,1,0
1788,3029,Classic Nail&Spa,2,False,Bangkok Metropolitan Region,10900,w4rw874,0,0.000000,0.0,...,NaN,NaN,11.0,NaN,NaN,NaN,NaN,0,0,0
1831,3104,ตอแหล Nail,2,False,Bangkok Metropolitan Region,NaN,w4rtg0d,0,5.000000,0.0,...,NaN,NaN,11.0,NaN,NaN,NaN,NaN,0,0,0
1882,3224,Jakrawal Salon,2,False,Bangkok Metropolitan Region,11000,w4rqyu7,0,4.190476,3.0,...,NaN,NaN,11.0,NaN,NaN,NaN,NaN,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
243267,335813,Barber Shop,2,False,Bangkok Metropolitan Region,NaN,w4rmytc,1,0.000000,0.0,...,NaN,NaN,12.0,NaN,NaN,NaN,NaN,0,0,0
243403,335965,ร้านนวดหัตถ์เงินหัตถ์ทอง,2,False,Chiang Mai,NaN,w5q6ugm,0,0.000000,0.0,...,NaN,NaN,13.0,NaN,NaN,NaN,NaN,0,0,0
243542,336117,โรงพยาบาลศัลยกรรมเกาหลีจิวเวลรี่,2,False,Bangkok Metropolitan Region,NaN,w4rw0kc,0,0.000000,0.0,...,NaN,NaN,12.0,NaN,NaN,NaN,NaN,0,0,0
243557,336133,ลับแล Spa & Massage,2,False,Bangkok Metropolitan Region,11000,w4rqzfy,1,0.000000,0.0,...,NaN,NaN,11.0,NaN,NaN,NaN,NaN,0,0,0
243824,336457,อิ๋วสปา,2,False,Bangkok Metropolitan Region,NaN,w4rw21q,0,0.000000,0.0,...,NaN,NaN,12.0,NaN,NaN,NaN,NaN,0,0,0
244076,336740,Fareeda Clinic,2,False,Bangkok Metropolitan Region,NaN,w4rw0jq,0,5.000000,0.0,...,NaN,NaN,12.0,NaN,NaN,NaN,NaN,0,0,0
244117,336793,Mee Tang Thai Massage,2,False,Bangkok Metropolitan Region,NaN,w4rwj1y,1,5.000000,0.0,...,NaN,NaN,12.0,NaN,NaN,NaN,NaN,0,0,0
244282,336990,M8 Eyelashes,2,False,Chiang Mai,NaN,w5q75bc,0,5.000000,0.0,...,NaN,NaN,11.0,NaN,NaN,NaN,NaN,0,0,0
244340,337064,Pretty Cozy Nail Cottage,2,False,Bangkok Metropolitan Region,10110,w4rw0u6,0,4.029412,0.0,...,NaN,NaN,11.0,NaN,NaN,NaN,NaN,0,0,0
244354,337084,เสนาเวชการคลินิก,2,False,Bangkok Metropolitan Region,10230,w4rw9mb,0,5.000000,0.0,...,NaN,NaN,13.0,NaN,NaN,NaN,NaN,0,0,0
244366,337098,House Of Nails,2,False,Chiang Mai,50300,w5q7j4f,0,3.000000,2.0,...,NaN,NaN,11.0,NaN,NaN,NaN,NaN,0,0,0
244435,337176,Fenails,2,False,Bangkok Metropolitan Region,10540,w4rt7st,0,5.000000,0.0,...,NaN,NaN,11.0,NaN,NaN,NaN,NaN,0,0,0
244458,337208,Por&Kwan Nails,2,False,Bangkok Metropolitan Region,NaN,w4rw26p,0,0.000000,0.0,...,NaN,NaN,11.0,NaN,NaN,NaN,NaN,1,0,0
244472,337224,Momo,2,False,Rayong,NaN,w4rbpuz,0,2.928571,0.0,...,NaN,NaN,11.0,NaN,NaN,NaN,NaN,0,0,0
244483,337241,In Balance Spa by Novotel Vintage Park,2,False,Phuket,83150,w1muuvu,0,5.000000,0.0,...,NaN,NaN,11.0,NaN,NaN,NaN,NaN,0,1,0
244590,337378,พราวnail,2,False,Bangkok Metropolitan Region,NaN,w4rmktr,1,5.000000,0.0,...,1.0,NaN,11.0,NaN,NaN,NaN,NaN,0,1,0
244642,337435,อนงค์วรรณ นวดแผนไทย & สปา,2,False,Bangkok Metropolitan Region,12130,w4rx3tj,1,5.000000,0.0,...,NaN,NaN,11.0,NaN,NaN,NaN,NaN,0,0,0
244793,337606,ตะไคร้หอม นวดแผนไทย&สปา,2,False,Bangkok Metropolitan Region,10700,w4rqqs7,0,4.285714,0.0,...,1.0,NaN,11.0,NaN,NaN,NaN,NaN,0,0,0
244886,337707,Florida Hair Design,2,False,Chiang Mai,50180,w5q7hmc,1,4.000000,0.0,...,NaN,NaN,11.0,NaN,NaN,NaN,NaN,0,0,0
244900,337724,Ck nails 1088,2,False,Bangkok Metropolitan Region,NaN,w4rqqep,0,5.000000,0.0,...,NaN,NaN,11.0,NaN,NaN,NaN,NaN,0,0,0
244906,337730,Training Ground,2,False,Bangkok Metropolitan Region,NaN,w4rw111,0,0.000000,0.0,...,NaN,NaN,13.0,NaN,NaN,NaN,NaN,0,0,0
245036,337872,Rainbow Nails,2,False,Chiang Mai,NaN,w5q6gge,1,0.000000,0.0,...,NaN,NaN,11.0,NaN,NaN,NaN,NaN,0,0,0
245144,337989,Pinktailz nail shop,2,False,สงขลา,90110,w1pry96,0,5.000000,0.0,...,NaN,NaN,11.0,NaN,NaN,NaN,NaN,0,1,0
245445,338327,The Heritage Boutique Spa,2,False,Bangkok Metropolitan Region,NaN,w4rw37h,1,4.000000,0.0,...,1.0,NaN,12.0,NaN,NaN,NaN,NaN,0,0,0
245631,338541,สามารถหัตถเวช,2,False,Bangkok Metropolitan Region,NaN,w4rmtx2,0,3.027397,0.0,...,1.0,NaN,12.0,NaN,NaN,NaN,NaN,0,0,0
245984,338936,เมย์ มาสสาจ แอน สปา,2,False,Chon Buri,20150,w4rc8fb,0,5.000000,0.0,...,1.0,NaN,11.0,NaN,NaN,NaN,NaN,0,1,0
246204,339172,Women’s Massage Center by Ex-Prisoners,2,False,Chiang Mai,NaN,w5q6ukx,0,0.000000,0.0,...,NaN,NaN,12.0,NaN,NaN,NaN,NaN,0,0,1
246431,339416,Power gold wax,2,False,Bangkok Metropolitan Region,10900,w4rw86d,0,4.000000,0.0,...,NaN,NaN,11.0,NaN,NaN,NaN,NaN,0,0,0
246524,339524,Professional Outcall Massage Bangkok,2,False,Bangkok Metropolitan Region,10110,w4rw0b0,0,0.000000,0.0,...,NaN,NaN,12.0,NaN,NaN,NaN,NaN,0,0,0
246742,339847,New nails,2,False,Bangkok Metropolitan Region,10800,w4rqzfs,0,3.032258,0.0,...,NaN,NaN,11.0,NaN,NaN,NaN,NaN,0,0,0

# 8. Group By -- Aggregation
https://www.kaggle.com/crawford/python-groupby-tutorial#

<img src="03.08-split-apply-combine.png">

In [ ]:
groups = search_click_df.groupby('business_id')

In [ ]:
groups

In [ ]:
groups.count()

,business_id,click_timestamp,search_id,display_position,time_diff_nanos,ads,bu_name
0,2.0,21,21,21,21,21,21
1,4.0,9,9,9,9,9,9
2,5.0,19,19,19,19,19,19
3,6.0,61,61,61,61,61,61
4,7.0,57,57,57,57,57,57
5,14.0,36,36,36,36,36,36
6,15.0,11,11,11,11,11,11
7,16.0,935,935,935,935,935,935
8,20.0,4,4,4,4,4,4
9,21.0,8,8,8,8,8,8
10,24.0,113,113,113,113,113,113
11,27.0,206,206,206,206,206,206
12,28.0,6,6,6,6,6,6
13,29.0,16,16,16,16,16,16
14,30.0,4,4,4,4,4,4
15,32.0,5,5,5,5,5,5
16,34.0,70,70,70,70,70,70
17,35.0,4,4,4,4,4,4
18,36.0,4,4,4,4,4,4
19,37.0,2,2,2,2,2,2
20,38.0,14,14,14,14,14,14
21,41.0,6,6,6,6,6,6
22,42.0,4,4,4,4,4,4
23,44.0,32,32,32,32,32,32
24,45.0,2,2,2,2,2,2
25,46.0,9,9,9,9,9,9
26,49.0,22,22,22,22,22,22
27,50.0,17,17,17,17,17,17
28,51.0,4,4,4,4,4,4
29,52.0,101,101,101,101,101,101
...,...,...,...,...,...,...,...
246817,340007.0,15,15,15,15,15,15
246818,340011.0,11,11,11,11,11,11
246819,340015.0,2,2,2,2,2,2
246820,340022.0,1,1,1,1,1,1
246821,340024.0,63,63,63,63,63,63
246822,340025.0,54,54,54,54,54,54
246823,340027.0,7,7,7,7,7,7
246824,340028.0,8,8,8,8,8,8
246825,340029.0,2,2,2,2,2,2
246826,340031.0,5,5,5,5,5,5
246827,340035.0,56,56,56,56,56,56
246828,340036.0,5,5,5,5,5,5
246829,340037.0,22,22,22,22,22,22
246830,340038.0,6,6,6,6,6,6
246831,340041.0,2,2,2,2,2,2
246832,340042.0,4,4,4,4,4,4
246833,340043.0,2,2,2,2,2,2
246834,340048.0,5,5,5,5,5,5
246835,340051.0,1,1,1,1,1,1
246836,340054.0,6,6,6,6,6,6
246837,340056.0,2,2,2,2,2,2
246838,340059.0,3,3,3,3,3,3
246839,340060.0,44,44,44,44,44,44
246840,340063.0,16,16,16,16,16,16
246841,340067.0,7,7,7,7,7,7
246842,340068.0,71,71,71,71,71,71
246843,340070.0,32,32,32,32,32,32
246844,340074.0,9,9,9,9,9,9
246845,340079.0,4,4,4,4,4,4
246846,340091.0,5,5,5,5,5,5

In [ ]:
count_table=groups.count().reset_index()

In [ ]:
w_restaurant_df['num_click'] = w_restaurant_df['id'].map(count_table.set_index('business_id')['ads'])

In [ ]:
w_restaurant_df

,id,name,domain_id,closed,city_name,zipcode,geohash,new_open,weighted_average_rating,number_of_chains,...,best_of_wongnai,number_of_seats,music_venue,hotel_restaurant,pet_friendly,delivery,wifi_0.0,wifi_1.0,wifi_2.0,num_click
0,2,นครินทร์ทันตกรรม,2,False,Samut Songkhram,75000,w4rh7g3,0,5.000000,0.0,...,NaN,13.0,NaN,NaN,NaN,NaN,0,0,0,21
4,7,Buono Caffe,1,False,Bangkok Metropolitan Region,10220,w4rx4gd,0,3.738462,0.0,...,NaN,2.0,NaN,NaN,NaN,NaN,0,1,0,57
5,14,บ้านมุมสบาย,1,False,Chon Buri,NaN,w4rgsyz,0,5.000000,0.0,...,NaN,5.0,1.0,0.0,0.0,0.0,0,1,0,36
7,16,Sazanami,1,False,Bangkok Metropolitan Region,10110,w4rw0sp,0,4.130435,0.0,...,NaN,2.0,NaN,NaN,NaN,NaN,0,0,0,935
9,21,นกน้ำเต้าหู้,1,False,Narathiwat,96000,w30kt51,0,3.000000,0.0,...,NaN,2.0,NaN,NaN,NaN,NaN,1,0,0,8
10,24,Rotee Me Chabu,1,False,Bangkok Metropolitan Region,12130,w4rx3ys,0,4.047619,0.0,...,NaN,2.0,NaN,NaN,NaN,NaN,1,0,0,113
11,27,แพอาหารธาราบุรี,1,False,Kanchanaburi,71000.0,w4qzbb4,0,3.568245,0.0,...,NaN,2.0,NaN,NaN,NaN,NaN,0,0,0,206
17,35,ก๋วยเตี๋ยวเย็นตาโฟเจ๊หมวย นครสวรรค์,1,False,Nakhon Sawan,60000,w4z1q7n,0,0.000000,0.0,...,NaN,3.0,NaN,NaN,NaN,NaN,0,1,0,4
20,38,บะหมี่ ลูกชิ้นปลา,1,False,Bangkok Metropolitan Region,10100,w4rqpk8,0,3.055556,0.0,...,NaN,2.0,NaN,NaN,NaN,NaN,1,0,0,14
22,42,ข้าวขาหมู ป้าเพ็ญ,1,False,Bangkok Metropolitan Region,NaN,w4rx0fh,0,5.000000,0.0,...,NaN,2.0,NaN,NaN,NaN,NaN,0,0,0,4
23,44,OMG OH MY GELATO,1,False,Bangkok Metropolitan Region,NaN,w4rqytp,0,3.700000,0.0,...,NaN,0.0,NaN,NaN,NaN,NaN,1,0,0,32
30,54,Angkor Aran,1,False,Sa Kaeo,10600,w62vv1d,0,0.000000,0.0,...,NaN,3.0,NaN,1.0,NaN,NaN,0,1,0,18
33,63,Ajitsukasa Nomura,1,False,Okayama-ken,NaN,wypjpw8,0,4.000000,0.0,...,NaN,2.0,NaN,NaN,NaN,NaN,1,0,0,12
36,70,Wrap Master,1,False,Chiang Mai,NaN,w5q6unc,0,3.629630,0.0,...,NaN,5.0,0.0,0.0,0.0,1.0,0,0,0,86
37,71,Let's Fry By เมียจ๋า,1,False,Bangkok Metropolitan Region,NaN,w4rqqq0,0,0.000000,0.0,...,NaN,1.0,NaN,NaN,NaN,NaN,0,0,0,5
50,96,กัปตันเทเบิลเทอเรส,1,False,Rayong,21160,w60peuj,0,3.000000,0.0,...,NaN,5.0,NaN,1.0,NaN,NaN,0,0,0,3
51,97,Nawamin,1,False,Bangkok Metropolitan Region,NaN,w4rwd6w,0,0.000000,0.0,...,NaN,1.0,NaN,NaN,NaN,NaN,1,0,0,2
55,102,ยุทธครัวไทย (ป่าไร่เรือนทอง),1,False,Chiang Rai,NaN,w5x1856,0,3.000000,0.0,...,NaN,3.0,NaN,NaN,NaN,NaN,1,0,0,13
60,111,เต-ชา ก๋วยเตี๋ยวไข่ไดโนเสาร์,1,False,Chiang Mai,NaN,w5qqhjs,0,3.984000,0.0,...,NaN,2.0,0.0,0.0,0.0,0.0,0,1,0,49
61,114,มานีมีนม,1,False,Bangkok Metropolitan Region,10312,w4rw3e0,0,3.793103,18.0,...,NaN,2.0,NaN,NaN,NaN,1.0,0,1,0,82
62,116,Zenna Thai And Japanese,1,False,Texas,NaN,9vff298,0,0.000000,0.0,...,NaN,5.0,NaN,NaN,NaN,NaN,0,1,0,3
68,125,Oldies Bar & Bistro,1,False,Chon Buri,20230,w4rf8du,0,0.000000,0.0,...,NaN,2.0,NaN,NaN,NaN,NaN,0,0,0,497
69,126,Dolce Italia,1,False,Chiang Rai,NaN,w5x18re,0,4.000000,0.0,...,NaN,1.0,NaN,NaN,NaN,NaN,1,0,0,60
70,128,ABC Kitchen,1,False,Bangkok Metropolitan Region,10120,w4rw010,0,4.000000,0.0,...,NaN,0.0,NaN,NaN,NaN,NaN,0,0,0,26
78,146,RJ.GRUNTS Burger&Fries,1,False,Illinois,NaN,dp3wb12,0,4.000000,0.0,...,NaN,0.0,NaN,NaN,NaN,NaN,0,1,0,5
81,149,WISH CLINIC,2,False,Khon Kaen,NaN,w6cj7qn,0,5.000000,0.0,...,NaN,11.0,NaN,NaN,NaN,NaN,0,1,0,14
82,154,Blue,1,False,Bangkok Metropolitan Region,NaN,w4rmvuv,0,0.000000,0.0,...,NaN,1.0,NaN,NaN,NaN,NaN,0,0,0,27
86,164,Beta House,1,False,Chon Buri,20130,w4rg88r,0,3.000000,0.0,...,NaN,2.0,NaN,NaN,NaN,NaN,0,0,0,28
91,175,ใต้ต้นมะม่วง,1,False,Phuket,83000,w1muz5d,0,3.857143,0.0,...,NaN,2.0,NaN,NaN,NaN,NaN,1,0,0,13
93,179,Sabai Thai Massage,2,False,Bangkok Metropolitan Region,NaN,w4rw654,0,3.000000,0.0,...,NaN,11.0,NaN,NaN,NaN,NaN,0,0,0,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
246730,339810,โอ๋โภชนา,1,False,Nakhon Sawan,60110,w4zd285,0,4.000000,0.0,...,NaN,1.0,NaN,NaN,NaN,NaN,0,0,0,11
246732,339815,ร้านโจ๊กนายฮุย,1,False,Bangkok Metropolitan Region,10700,w4rqq0q,0,0.000000,0.0,...,NaN,1.0,NaN,NaN,NaN,NaN,1,0,0,3
246738,339837,ครัวโกดัง,1,False,Kanchanaburi,NaN,w4wbkes,0,3.055556,0.0,...,NaN,2.0,NaN,NaN,NaN,NaN,0,0,0,28
246742,339847,New nails,2,False,Bangkok Metropolitan Region,10800,w4rqzfs,0,3.032258,0.0,...,NaN,11.0,NaN,NaN,NaN,NaN,0,0,0,27
246757,339876,เจ๊นิจ สาขา 2 ปตท.คูเมือง,1,False,Suphan Buri,72000,w4x4q50,0,4.000000,0.0,...,NaN,3.0,NaN,NaN,NaN,NaN,0,0,0,32
246758,339877,Aluco Coffee,1,False,Bangkok Metropolitan Region,NaN,w4rtuss,0,5.000000,0.0,...,NaN,3.0,NaN,NaN,NaN,NaN,0,0,0,2
246761,339881,ขนมเข่งทอด เจ๊หงส์,1,False,Phetchaburi,NaN,w4r4d3u,0,0.000000,0.0,...,NaN,0.0,NaN,NaN,NaN,NaN,0,0,0,9
246762,339882,ส้มตำริมสระหนองบัว,1,False,Surin,NaN,w69senq,0,5.000000,0.0,...,NaN,2.0,NaN,NaN,NaN,NaN,0,1,0,3
246764,339885,ครัวสามหนุ่ม,1,False,Bangkok Metropolitan Region,10310,w4rw2wu,0,4.000000,0.0,...,NaN,3.0,NaN,NaN,NaN,NaN,1,0,0,4
246770,339895,Café Terrace,1,False,Chon Buri,20110,w4rfdk1,0,0.000000,0.0,...,NaN,4.0,NaN,1.0,NaN,NaN,0,1,0,33
246773,339901,Sobok,1,False,Incheon,NaN,wy9vj3n,0,4.500000,0.0,...,NaN,3.0,NaN,NaN,NaN,NaN,0,1,0,7
246774,339903,แดงขนมเบื้อง,1,False,Bangkok Metropolitan Region,10600,w4rqngz,0,4.000000,0.0,...,NaN,0.0,NaN,0.0,NaN,NaN,1,0,0,22
246775,339904,Pondok Tempo Doeloe,1,False,Bali,80361,qw3ymhg,0,3.000000,0.0,...,NaN,5.0,NaN,NaN,NaN,NaN,1,0,0,5
246788,339934,Silla,1,False,Scotland,NaN,gcuvy3z,0,5.000000,0.0,...,NaN,3.0,NaN,NaN,NaN,NaN,1,0,0,20
246791,339937,ยู้ ลูกชิ้นปลาเยาวราช,1,False,เขาใหญ่,26000,w4xbz45,0,2.500000,0.0,...,NaN,3.0,NaN,NaN,NaN,NaN,0,0,0,24
246792,339938,ลาบชาววัง,1,False,Ubon Ratchathani,NaN,w6dwdkv,0,2.909091,0.0,...,NaN,3.0,NaN,NaN,NaN,NaN,0,1,0,3
246793,339939,ส้มตำกันเอง มด&เนะ,1,False,Suphan Buri,72000,w4x4q1j,0,4.000000,0.0,...,NaN,2.0,NaN,NaN,NaN,NaN,1,0,0,22
246797,339943,Café in Mind,1,False,Sukhothai,NaN,w5nf99m,1,5.000000,0.0,...,NaN,2.0,0.0,0.0,0.0,0.0,0,1,0,59
246801,339953,Best Bar,1,False,Bangkok Metropolitan Region,73170,w4rqd8x,0,3.000000,0.0,...,NaN,3.0,NaN,NaN,NaN,NaN,0,0,0,455
246802,339955,Gaa,1,False,Bangkok Metropolitan Region,10330,w4rqpuu,0,4.103250,0.0,...,NaN,2.0,0.0,0.0,NaN,0.0,0,0,0,57
246806,339965,เดอนัว ส้มตำ ไก่ย่างเขาสวนกวาง,1,False,Bangkok Metropolitan Region,NaN,w4rmfps,1,0.000000,0.0,...,NaN,3.0,NaN,NaN,NaN,NaN,0,0,0,29
246809,339980,Star Hotel Rayong,1,False,Rayong,21000.0,w6200mr,0,0.000000,0.0,...,NaN,5.0,NaN,1.0,NaN,NaN,0,1,0,6
246813,339998,TOONGs COFFEE Roasters,1,False,Chiang Mai,50230,w5q6e0g,0,0.000000,0.0,...,NaN,1.0,NaN,NaN,NaN,NaN,0,0,1,7
246821,340024,ผู้ชายขายหอย,1,False,Bangkok Metropolitan Region,NaN,w4rwj1f,0,0.000000,0.0,...,NaN,2.0,NaN,NaN,NaN,NaN,0,0,1,63
246826,340031,ลาบเขยยอง,1,False,Chiang Mai,NaN,w5q6ws4,0,3.000000,0.0,...,NaN,4.0,NaN,NaN,NaN,NaN,0,1,0,5
246827,340035,สำราญโภชนา อตก.,1,False,Bangkok Metropolitan Region,10900.0,w4rw2p8,0,4.483871,0.0,...,NaN,1.0,NaN,NaN,NaN,NaN,0,0,0,56
246829,340037,Fatboy's Burger Bar,1,False,Kamphaeng Phet,NaN,w4yv8z6,0,4.357143,0.0,...,NaN,1.0,NaN,NaN,NaN,NaN,0,0,0,22
246836,340054,คนึงหา,1,False,Phatthalung,NaN,w1r5m7j,0,4.000000,0.0,...,NaN,2.0,NaN,NaN,NaN,NaN,0,1,0,6
246839,340060,ส้มตำเวียงจันทร์,1,False,Lampang,NaN,w5qb02b,1,3.032258,0.0,...,NaN,2.0,NaN,NaN,NaN,NaN,1,0,0,44
246843,340070,สะบายดี คาราโอเกะ,1,False,Bangkok Metropolitan Region,NaN,w4rwjcg,0,0.000000,0.0,...,NaN,2.0,NaN,NaN,NaN,NaN,0,0,0,32

In [ ]:
## Build a table which only shows id, name, rating, num_clicks. How?

# ~~9. Randomly select data~~

In [ ]:
w_restaurant_df.sample(n=3) ## This is only view of the result

,id,name,domain_id,closed,city_name,zipcode,geohash,new_open,weighted_average_rating,number_of_chains,...,best_of_wongnai,number_of_seats,music_venue,hotel_restaurant,pet_friendly,delivery,wifi_0.0,wifi_1.0,wifi_2.0,num_click
121798,179673,คั่วกลิ้ง + ผักสด ข้าวแกงปักษ์ใต้เมืองคอน สาขา 2,1,True,Bangkok Metropolitan Region,NaN,w4rqed2,0,4.913043,0.0,...,NaN,2.0,NaN,NaN,NaN,NaN,0,0,0,8
206691,287896,ทรายสีชมพู,2,False,Bangkok Metropolitan Region,10700,w4rqqe4,0,4.000000,0.0,...,NaN,11.0,NaN,NaN,NaN,NaN,0,0,0,11
26554,42141,ระเบียงน้ำ @ธาตุพนม,1,False,Nakhon Phanom,NaN,w742r5v,0,4.000000,0.0,...,NaN,3.0,NaN,NaN,NaN,NaN,0,1,0,23

# 9.5 Selecting values in table like a matrix
.loc[,]->value iloc[[]]->records

In [ ]:
w_restaurant_df

,id,name,domain_id,closed,city_name,zipcode,geohash,new_open,weighted_average_rating,number_of_chains,...,good_for_groups,good_for_kids,bookable,best_of_wongnai,wifi,number_of_seats,music_venue,hotel_restaurant,pet_friendly,delivery
0,2,นครินทร์ทันตกรรม,2,0,Samut Songkhram,75000,w4rh7g3,0,5.000000,NaN,...,NaN,NaN,NaN,NaN,NaN,13.0,NaN,NaN,NaN,NaN
1,4,Corner House,1,0,Bangkok Metropolitan Region,12150,w4rx73h,0,2.000000,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,5,วัดโลกยสุธาราม,4,0,Phra Nakhon Si Ayutthaya,13000,w4x98jk,0,4.000000,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,6,นันท์คาราโอเกะ,1,0,Bangkok Metropolitan Region,10700,w4rqw9q,0,0.000000,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,7,Buono Caffe,1,0,Bangkok Metropolitan Region,10220,w4rx4gd,0,3.738462,NaN,...,NaN,NaN,NaN,NaN,1.0,2.0,NaN,NaN,NaN,NaN
5,14,บ้านมุมสบาย,1,0,Chon Buri,NaN,w4rgsyz,0,5.000000,NaN,...,1.0,1.0,1.0,NaN,1.0,5.0,1.0,0.0,0.0,0.0
6,15,Hing Fat Resteurant,1,0,New Territories,NaN,wecny4b,0,3.000000,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,16,Sazanami,1,0,Bangkok Metropolitan Region,10110,w4rw0sp,0,4.130435,NaN,...,1.0,1.0,NaN,NaN,NaN,2.0,NaN,NaN,NaN,NaN
8,20,ครัวทิพวัลย์,1,0,Krabi,81170,w1qe9m1,0,0.000000,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,21,นกน้ำเต้าหู้,1,0,Narathiwat,96000,w30kt51,0,3.000000,NaN,...,NaN,NaN,NaN,NaN,0.0,2.0,NaN,NaN,NaN,NaN
10,24,Rotee Me Chabu,1,0,Bangkok Metropolitan Region,12130,w4rx3ys,0,4.047619,NaN,...,1.0,1.0,1.0,NaN,0.0,2.0,NaN,NaN,NaN,NaN
11,27,แพอาหารธาราบุรี,1,0,Kanchanaburi,71000,w4qzbb4,0,3.568245,NaN,...,1.0,1.0,1.0,NaN,NaN,2.0,NaN,NaN,NaN,NaN
12,28,Milkcow,1,0,Singapore,NaN,w21z7he,0,5.000000,NaN,...,1.0,1.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,29,Jeep Came อาหารป่า & ดนตรี,1,0,Bangkok Metropolitan Region,NaN,w4rqvbq,0,0.000000,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,30,The Coffee Shop,1,0,เขาใหญ่,NaN,w4xbuyk,0,0.000000,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN
15,32,The Rabbit หมูกระทะนานาชาติ,1,0,Chon Buri,20110,w4rfc75,0,2.846154,NaN,...,1.0,1.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,34,Mott 32,1,0,New Territories,NaN,wecnvb0,0,4.513072,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,35,ก๋วยเตี๋ยวเย็นตาโฟเจ๊หมวย นครสวรรค์,1,0,Nakhon Sawan,60000,w4z1q7n,0,0.000000,NaN,...,1.0,1.0,0.0,NaN,1.0,3.0,NaN,NaN,NaN,NaN
18,36,ร้านผักบุ้งบิน,1,0,Phitsanulok,65000,w4zr9kq,0,1.000000,NaN,...,1.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,37,ลาวชง,1,0,Bangkok Metropolitan Region,73000,w4rnsdr,0,1.000000,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20,38,บะหมี่ ลูกชิ้นปลา,1,0,Bangkok Metropolitan Region,10100,w4rqpk8,0,3.055556,NaN,...,NaN,NaN,NaN,NaN,0.0,2.0,NaN,NaN,NaN,NaN
21,41,ธัญรส สาขา 27,1,0,Phitsanulok,65000,w4zr9vu,0,4.000000,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22,42,ข้าวขาหมู ป้าเพ็ญ,1,0,Bangkok Metropolitan Region,NaN,w4rx0fh,0,5.000000,NaN,...,NaN,NaN,NaN,NaN,NaN,2.0,NaN,NaN,NaN,NaN
23,44,OMG OH MY GELATO,1,0,Bangkok Metropolitan Region,NaN,w4rqytp,0,3.700000,NaN,...,1.0,1.0,0.0,NaN,0.0,0.0,NaN,NaN,NaN,NaN
24,45,ลุงตุ๊เจ้าเก่า,1,0,Phra Nakhon Si Ayutthaya,13110,w4x6htj,0,0.000000,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25,46,Music Cofe,1,0,Chiang Rai,57100,w5x1ccc,0,4.000000,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26,49,ขส. สเต็ก,1,0,Bangkok Metropolitan Region,10300,w4rqrwg,0,2.714286,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27,50,ร้านป้าเล็ก ก๋วยจั๊บ คลองบางหลวง,1,0,Bangkok Metropolitan Region,NaN,w4rqnk7,0,3.666667,NaN,...,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN
28,51,โรงแรมมนต์ระวีพาวิเลี่ยนรีสอร์ท,1,0,Phitsanulok,65000,w4zrc0c,0,0.000000,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN
29,52,A Day in Summer,1,0,Bangkok Metropolitan Region,10600,w4rqnwh,0,3.392344,NaN,...,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
246817,340007,Ruj's Coffee,1,0,Chiang Rai,NaN,w5x4116,0,2.627451,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
246818,340011,Coffman,1,0,Khon Kaen,40000,w6cjkqy,0,3.000000,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
246819,340015,ลากูนเทอเรซ,1,0,Surat Thani,84320,w1xnm05,0,0.000000,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
246820,340022,Riliro's,1,0,Ōsaka-fu,NaN,xn0m5qv,0,0.000000,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
246821,340024,ผู้ชายขายหอย,1,0,Bangkok Metropolitan Region,NaN,w4rwj1f,0,0.000000,NaN,...,1.0,1.0,1.0,NaN,2.0,2.0,NaN,NaN,NaN,NaN
246822,340025,Chang Xing,1,0,Bangkok Metropolitan Region,NaN,w4rqpwp,0,4.000000,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
246823,340027,Takumi-chaya,1,0,Gifu-ken,NaN,xn3tek5,0,4.000000,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
246824,340028,โรงแรมทาวน์อินทาวน์พัทยา,1,0,Chon Buri,20150,w4rc84b,0,0.000000,NaN,...,1.0,NaN,1.0,NaN,NaN,NaN,NaN,1.0,NaN,NaN
246825,340029,โค้งลาบเป็ด,1,0,Nakhon Phanom,48000,w74d8r1,0,0.000000,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
246826,340031,ลาบเขยยอง,1,0,Chiang Mai,NaN,w5q6ws4,0,3.000000,NaN,...,NaN,NaN,NaN,NaN,1.0,4.0,NaN,NaN,NaN,NaN
246827,340035,สำราญโภชนา อตก.,1,0,Bangkok Metropolitan Region,10900,w4rw2p8,0,4.483871,NaN,...,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN
246828,340036,แพอลิสา,1,0,Kanchanaburi,71000,w4qz9h0,0,0.000000,NaN,...,1.0,1.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
246829,340037,Fatboy's Burger Bar,1,0,Kamphaeng Phet,NaN,w4yv8z6,0,4.357143,NaN,...,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN
246830,340038,ดิ อิมพีเรียล หัวหิน บีชรีสอร์ท,3,0,Hua Hin,77110,w4ppdt8,0,0.000000,NaN,...,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,0.0,NaN
246831,340041,ครัวศาลายา,1,0,Bangkok Metropolitan Region,70110,w4rn1xk,0,0.000000,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
246832,340042,โชคดีกาแฟ,1,0,เขาใหญ่,25000,w62pfyd,0,5.000000,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
246833,340043,เบอร์นีบาร์,1,0,Surat Thani,84140,w1xjusn,0,0.000000,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
246834,340048,Kuppadeli,1,1,Bangkok Metropolitan Region,10110,w4rw0e8,0,0.000000,5.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
246835,340051,ร้านครัวแกงป่า,1,0,Bangkok Metropolitan Region,11110,w4rr7tm,0,0.000000,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
246836,340054,คนึงหา,1,0,Phatthalung,NaN,w1r5m7j,0,4.000000,NaN,...,1.0,1.0,0.0,NaN,1.0,2.0,NaN,NaN,NaN,NaN
246837,340056,บึงกาฬลาบก้อย,1,0,Bueng Kan,38000,w738qxw,0,0.000000,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
246838,340059,ลีลาวดี,1,0,Rayong,20180,w4rb77u,0,0.000000,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
246839,340060,ส้มตำเวียงจันทร์,1,0,Lampang,NaN,w5qb02b,1,3.032258,NaN,...,NaN,NaN,NaN,NaN,0.0,2.0,NaN,NaN,NaN,NaN
246840,340063,โตข้าวต้มปลา,1,0,Bangkok Metropolitan Region,NaN,w4rmur2,0,0.000000,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
246841,340067,Toffy home,1,0,Phetchabun,67000,w4zvmve,0,3.000000,NaN,...,1.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
246842,340068,Sushi Tama,1,0,Bangkok Metropolitan Region,11130,w4rqtcb,0,3.663522,3.0,...,0.0,1.0,0.0,NaN,0.0,NaN,NaN,NaN,NaN,NaN
246843,340070,สะบายดี คาราโอเกะ,1,0,Bangkok Metropolitan Region,NaN,w4rwjcg,0,0.000000,NaN,...,1.0,NaN,1.0,NaN,NaN,2.0,NaN,NaN,NaN,NaN
246844,340074,สเต็กแม่&กาแฟลูก,1,0,Bangkok Metropolitan Region,10160,w4rmvxf,0,4.000000,NaN,...,1.0,1.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
246845,340079,Mom Made,1,0,Nakhon Si Thammarat,80000,w1x04g6,0,5.000000,NaN,...,1.0,1.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
246846,340091,ก๋วยเตี๋ยวหมูน้ำตก ก๋วยเตี๋ยวเรือทอง,1,0,Suphan Buri,72000,w4x4q7s,0,3.000000,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
w_restaurant_df.iloc[2:5,2:4]

   domain_id  closed
2          4       0
3          1       0
4          1       0

# 10 Create table
<img src="52835793_259306464964511_3851804852342489088_n.png">

# ~~10. Extract date-time~~
### https://stackoverflow.com/questions/39662149/pandas-extract-date-and-time-from-timestamp 
### https://stackoverflow.com/questions/11302013/python-datetime-strptime-ignore-fraction-of-a-second

## ~~11. Sort record based on values in a column~~

# 12. Save to use with other applications

In [ ]:
search_click_df.to_csv('search_click_extracted_time.csv')

<img src="panda_end2.jpg"> 
jupyter nbconvert "Basic ELT with Pandas.ipynb" --to pdf

## Extra1 String manipulations
.format .replace

In [ ]:
a = 'Bangkok'

In [ ]:
'i love {}.csv'.format(a)

'i love Bangkok.csv'

In [ ]:
'   bangkok' == 'bangkok'

False

In [ ]:
'     b a n g k o k'.replace(' ','')

'bangkok'

## ~~Extra2 Map visualization~~

https://www.kdnuggets.com/2018/09/visualising-geospatial-data-python-folium.html

In [ ]:
import folium
import pandas as pd

In [ ]:
country_geo = 'world.json'

In [ ]:
data = pd.read_csv('Indicators.csv')

In [ ]:
data

,CountryName,CountryCode,IndicatorName,IndicatorCode,Year,Value
0,Arab World,ARB,"Adolescent fertility rate (births per 1,000 wo...",SP.ADO.TFRT,1960,1.335609e+02
1,Arab World,ARB,Age dependency ratio (% of working-age populat...,SP.POP.DPND,1960,8.779760e+01
2,Arab World,ARB,"Age dependency ratio, old (% of working-age po...",SP.POP.DPND.OL,1960,6.634579e+00
3,Arab World,ARB,"Age dependency ratio, young (% of working-age ...",SP.POP.DPND.YG,1960,8.102333e+01
4,Arab World,ARB,Arms exports (SIPRI trend indicator values),MS.MIL.XPRT.KD,1960,3.000000e+06

In [ ]:
# select Life expectancy for females for all countries in 2013
hist_indicator =  'Life expectancy at birth'
hist_year = 2013

mask1 = data['IndicatorName'].str.contains(hist_indicator) 
mask2 = data['Year'].isin([hist_year])

# apply our mask
stage = data[mask1 & mask2]
stage.head()

#Creating a data frame with just the country codes and the values we want plotted.
data_to_plot = stage[['CountryCode','Value','CountryName']]
data_to_plot.head()

# labelling the legend
hist_indicator = stage.iloc[0]['IndicatorName']

In [ ]:
data_to_plot.head()

        CountryCode      Value             CountryName
5377669         ARB  72.536117              Arab World
5377670         ARB  68.848383              Arab World
5377671         ARB  70.631305              Arab World
5378129         CSS  74.757382  Caribbean small states
5378130         CSS  69.183365  Caribbean small states

## Extra2 Map visualization
https://www.kdnuggets.com/2018/09/visualising-geospatial-data-python-folium.html
https://github.com/python-visualization/folium/blob/master/examples/GeoJSON_and_choropleth.ipynb

In [ ]:
import folium
import pandas as pd

In [ ]:
data_to_plot = pd.read_csv('worlddata.csv')

In [ ]:
data_to_plot.head()

   Unnamed: 0 CountryCode      Value             CountryName
0     5377669         ARB  72.536117              Arab World
1     5377670         ARB  68.848383              Arab World
2     5377671         ARB  70.631305              Arab World
3     5378129         CSS  74.757382  Caribbean small states
4     5378130         CSS  69.183365  Caribbean small states

In [ ]:
country_geo = 'world.json'

In [ ]:
map = folium.Map(location=[100, 0], zoom_start=1.5)

In [ ]:
map

In [ ]:
map.choropleth(geo_data='world.json', data=data_to_plot,
             columns=['CountryName', 'Value'],
             key_on='feature.properties.name',
             fill_color='YlGnBu', fill_opacity=0.7, line_opacity=0.2,
             legend_name='dying age')

C:\ProgramData\Anaconda2\lib\site-packages\folium\folium.py:432: FutureWarning: The choropleth  method has been deprecated. Instead use the new Choropleth class, which has the same arguments. See the example notebook 'GeoJSON_and_choropleth' for how to do this.
  FutureWarning

In [ ]:
map.save('plot_data.html')

In [ ]:
from IPython.display import HTML
HTML('<iframe src=plot_data.html width=700 height=450></iframe>')

In [ ]:
#data_to_plot.to_csv('worlddata.csv')

# Test with thailand

In [ ]:
import json

In [ ]:
with open('prov_th.json', 'r') as fp:
    jsondatath = json.load(fp)

In [ ]:
jsondatath['th']['changwats']

[{u'name': u'\u0e01\u0e23\u0e38\u0e07\u0e40\u0e17\u0e1e\u0e21\u0e2b\u0e32\u0e19\u0e04\u0e23',
  u'pid': u'10'},
 {u'name': u'\u0e2a\u0e21\u0e38\u0e17\u0e23\u0e1b\u0e23\u0e32\u0e01\u0e32\u0e23',
  u'pid': u'11'},
 {u'name': u'\u0e19\u0e19\u0e17\u0e1a\u0e38\u0e23\u0e35', u'pid': u'12'},
 {u'name': u'\u0e1b\u0e17\u0e38\u0e21\u0e18\u0e32\u0e19\u0e35', u'pid': u'13'},
 {u'name': u'\u0e1e\u0e23\u0e30\u0e19\u0e04\u0e23\u0e28\u0e23\u0e35\u0e2d\u0e22\u0e38\u0e18\u0e22\u0e32',
  u'pid': u'14'},
 {u'name': u'\u0e2d\u0e48\u0e32\u0e07\u0e17\u0e2d\u0e07', u'pid': u'15'},
 {u'name': u'\u0e25\u0e1e\u0e1a\u0e38\u0e23\u0e35', u'pid': u'16'},
 {u'name': u'\u0e2a\u0e34\u0e07\u0e2b\u0e4c\u0e1a\u0e38\u0e23\u0e35',
  u'pid': u'17'},
 {u'name': u'\u0e0a\u0e31\u0e22\u0e19\u0e32\u0e17', u'pid': u'18'},
 {u'name': u'\u0e2a\u0e23\u0e30\u0e1a\u0e38\u0e23\u0e35', u'pid': u'19'},
 {u'name': u'\u0e0a\u0e25\u0e1a\u0e38\u0e23\u0e35', u'pid': u'20'},
 {u'name': u'\u0e23\u0e30\u0e22\u0e2d\u0e07', u'pid': u'21'},
 {u'name': u'\u0e08\u0e31\u0e19\u0e17\u0e1a\u0e38\u0e23\u0e35', u'pid': u'22'},
 {u'name': u'\u0e15\u0e23\u0e32\u0e14', u'pid': u'23'},
 {u'name': u'\u0e09\u0e30\u0e40\u0e0a\u0e34\u0e07\u0e40\u0e17\u0e23\u0e32',
  u'pid': u'24'},
 {u'name': u'\u0e1b\u0e23\u0e32\u0e08\u0e35\u0e19\u0e1a\u0e38\u0e23\u0e35',
  u'pid': u'25'},
 {u'name': u'\u0e19\u0e04\u0e23\u0e19\u0e32\u0e22\u0e01', u'pid': u'26'},
 {u'name': u'\u0e2a\u0e23\u0e30\u0e41\u0e01\u0e49\u0e27', u'pid': u'27'},
 {u'name': u'\u0e19\u0e04\u0e23\u0e23\u0e32\u0e0a\u0e2a\u0e35\u0e21\u0e32',
  u'pid': u'30'},
 {u'name': u'\u0e1a\u0e38\u0e23\u0e35\u0e23\u0e31\u0e21\u0e22\u0e4c',
  u'pid': u'31'},
 {u'name': u'\u0e2a\u0e38\u0e23\u0e34\u0e19\u0e17\u0e23\u0e4c', u'pid': u'32'},
 {u'name': u'\u0e28\u0e23\u0e35\u0e2a\u0e30\u0e40\u0e01\u0e29', u'pid': u'33'},
 {u'name': u'\u0e2d\u0e38\u0e1a\u0e25\u0e23\u0e32\u0e0a\u0e18\u0e32\u0e19\u0e35',
  u'pid': u'34'},
 {u'name': u'\u0e22\u0e42\u0e2a\u0e18\u0e23', u'pid': u'35'},
 {u'name': u'\u0e0a\u0e31\u0e22\u0e20\u0e39\u0e21\u0e34', u'pid': u'36'},
 {u'name': u'\u0e2d\u0e33\u0e19\u0e32\u0e08\u0e40\u0e08\u0e23\u0e34\u0e0d',
  u'pid': u'37'},
 {u'name': u'\u0e1a\u0e36\u0e07\u0e01\u0e32\u0e2c', u'pid': u'38'},
 {u'name': u'\u0e2b\u0e19\u0e2d\u0e07\u0e1a\u0e31\u0e27\u0e25\u0e33\u0e20\u0e39',
  u'pid': u'39'},
 {u'name': u'\u0e02\u0e2d\u0e19\u0e41\u0e01\u0e48\u0e19', u'pid': u'40'},
 {u'name': u'\u0e2d\u0e38\u0e14\u0e23\u0e18\u0e32\u0e19\u0e35', u'pid': u'41'},
 {u'name': u'\u0e40\u0e25\u0e22', u'pid': u'42'},
 {u'name': u'\u0e2b\u0e19\u0e2d\u0e07\u0e04\u0e32\u0e22', u'pid': u'43'},
 {u'name': u'\u0e21\u0e2b\u0e32\u0e2a\u0e32\u0e23\u0e04\u0e32\u0e21',
  u'pid': u'44'},
 {u'name': u'\u0e23\u0e49\u0e2d\u0e22\u0e40\u0e2d\u0e47\u0e14', u'pid': u'45'},
 {u'name': u'\u0e01\u0e32\u0e2c\u0e2a\u0e34\u0e19\u0e18\u0e38\u0e4c',
  u'pid': u'46'},
 {u'name': u'\u0e2a\u0e01\u0e25\u0e19\u0e04\u0e23', u'pid': u'47'},
 {u'name': u'\u0e19\u0e04\u0e23\u0e1e\u0e19\u0e21', u'pid': u'48'},
 {u'name': u'\u0e21\u0e38\u0e01\u0e14\u0e32\u0e2b\u0e32\u0e23', u'pid': u'49'},
 {u'name': u'\u0e40\u0e0a\u0e35\u0e22\u0e07\u0e43\u0e2b\u0e21\u0e48',
  u'pid': u'50'},
 {u'name': u'\u0e25\u0e33\u0e1e\u0e39\u0e19', u'pid': u'51'},
 {u'name': u'\u0e25\u0e33\u0e1b\u0e32\u0e07', u'pid': u'52'},
 {u'name': u'\u0e2d\u0e38\u0e15\u0e23\u0e14\u0e34\u0e15\u0e16\u0e4c',
  u'pid': u'53'},
 {u'name': u'\u0e41\u0e1e\u0e23\u0e48', u'pid': u'54'},
 {u'name': u'\u0e19\u0e48\u0e32\u0e19', u'pid': u'55'},
 {u'name': u'\u0e1e\u0e30\u0e40\u0e22\u0e32', u'pid': u'56'},
 {u'name': u'\u0e40\u0e0a\u0e35\u0e22\u0e07\u0e23\u0e32\u0e22', u'pid': u'57'},
 {u'name': u'\u0e41\u0e21\u0e48\u0e2e\u0e48\u0e2d\u0e07\u0e2a\u0e2d\u0e19',
  u'pid': u'58'},
 {u'name': u'\u0e19\u0e04\u0e23\u0e2a\u0e27\u0e23\u0e23\u0e04\u0e4c',
  u'pid': u'60'},
 {u'name': u'\u0e2d\u0e38\u0e17\u0e31\u0e22\u0e18\u0e32\u0e19\u0e35',
  u'pid': u'61'},
 {u'name': u'\u0e01\u0e33\u0e41\u0e1e\u0e07\u0e40\u0e1e\u0e0a\u0e23',
  u'pid': u'62'},
 {u'name': u'\u0e15\u0e32\u0e01', u'pid': u'63'},
 {u'name': u'\u0e2a\u0e38\u0e42\u0e02\u0e17\u0e31\u0e22', u'pid': u'64'},
 {u'name': u'\u0e1e\u0e34\u0e29\u0e13\u0e38\u0e42\u0e25\u0e01', u'pid': u'65'},
 {u'name': u'\u0e1e\u0e34\u0e08\u0e34\u0e15\u0e23', u'pid': u'66'},
 {u'name': u'\u0e40\u0e1e\u0e0a\u0e23\u0e1a\u0e39\u0e23\u0e13\u0e4c',
  u'pid': u'67'},
 {u'name': u'\u0e23\u0e32\u0e0a\u0e1a\u0e38\u0e23\u0e35', u'pid': u'70'},
 {u'name': u'\u0e01\u0e32\u0e0d\u0e08\u0e19\u0e1a\u0e38\u0e23\u0e35',
  u'pid': u'71'},
 {u'name': u'\u0e2a\u0e38\u0e1e\u0e23\u0e23\u0e13\u0e1a\u0e38\u0e23\u0e35',
  u'pid': u'72'},
 {u'name': u'\u0e19\u0e04\u0e23\u0e1b\u0e10\u0e21', u'pid': u'73'},
 {u'name': u'\u0e2a\u0e21\u0e38\u0e17\u0e23\u0e2a\u0e32\u0e04\u0e23',
  u'pid': u'74'},
 {u'name': u'\u0e2a\u0e21\u0e38\u0e17\u0e23\u0e2a\u0e07\u0e04\u0e23\u0e32\u0e21',
  u'pid': u'75'},
 {u'name': u'\u0e40\u0e1e\u0e0a\u0e23\u0e1a\u0e38\u0e23\u0e35', u'pid': u'76'},
 {u'name': u'\u0e1b\u0e23\u0e30\u0e08\u0e27\u0e1a\u0e04\u0e35\u0e23\u0e35\u0e02\u0e31\u0e19\u0e18\u0e4c',
  u'pid': u'77'},
 {u'name': u'\u0e19\u0e04\u0e23\u0e28\u0e23\u0e35\u0e18\u0e23\u0e23\u0e21\u0e23\u0e32\u0e0a',
  u'pid': u'80'},
 {u'name': u'\u0e01\u0e23\u0e30\u0e1a\u0e35\u0e48', u'pid': u'81'},
 {u'name': u'\u0e1e\u0e31\u0e07\u0e07\u0e32', u'pid': u'82'},
 {u'name': u'\u0e20\u0e39\u0e40\u0e01\u0e47\u0e15', u'pid': u'83'},
 {u'name': u'\u0e2a\u0e38\u0e23\u0e32\u0e29\u0e0e\u0e23\u0e4c\u0e18\u0e32\u0e19\u0e35',
  u'pid': u'84'},
 {u'name': u'\u0e23\u0e30\u0e19\u0e2d\u0e07', u'pid': u'85'},
 {u'name': u'\u0e0a\u0e38\u0e21\u0e1e\u0e23', u'pid': u'86'},
 {u'name': u'\u0e2a\u0e07\u0e02\u0e25\u0e32', u'pid': u'90'},
 {u'name': u'\u0e2a\u0e15\u0e39\u0e25', u'pid': u'91'},
 {u'name': u'\u0e15\u0e23\u0e31\u0e07', u'pid': u'92'},
 {u'name': u'\u0e1e\u0e31\u0e17\u0e25\u0e38\u0e07', u'pid': u'93'},
 {u'name': u'\u0e1b\u0e31\u0e15\u0e15\u0e32\u0e19\u0e35', u'pid': u'94'},
 {u'name': u'\u0e22\u0e30\u0e25\u0e32', u'pid': u'95'},
 {u'name': u'\u0e19\u0e23\u0e32\u0e18\u0e34\u0e27\u0e32\u0e2a', u'pid': u'96'}]

In [ ]:
th_tab=pd.DataFrame(jsondatath['th']['changwats'])

In [ ]:
th_tab

               name pid
0     กรุงเทพมหานคร  10
1       สมุทรปราการ  11
2           นนทบุรี  12
3          ปทุมธานี  13
4   พระนครศรีอยุธยา  14
5           อ่างทอง  15
6            ลพบุรี  16
7         สิงห์บุรี  17
8            ชัยนาท  18
9           สระบุรี  19
10           ชลบุรี  20
11            ระยอง  21
12         จันทบุรี  22
13             ตราด  23
14       ฉะเชิงเทรา  24
15       ปราจีนบุรี  25
16          นครนายก  26
17          สระแก้ว  27
18       นครราชสีมา  30
19        บุรีรัมย์  31
20         สุรินทร์  32
21         ศรีสะเกษ  33
22      อุบลราชธานี  34
23            ยโสธร  35
24          ชัยภูมิ  36
25       อำนาจเจริญ  37
26           บึงกาฬ  38
27      หนองบัวลำภู  39
28          ขอนแก่น  40
29         อุดรธานี  41
..              ...  ..
47        นครสวรรค์  60
48        อุทัยธานี  61
49        กำแพงเพชร  62
50              ตาก  63
51          สุโขทัย  64
52         พิษณุโลก  65
53           พิจิตร  66
54        เพชรบูรณ์  67
55          ราชบุรี  70
56        กาญจนบุรี  71
57       สุพรรณบุรี  72
58           นครปฐม  73
59        สมุทรสาคร  74
60      สมุทรสงคราม  75
61         เพชรบุรี  76
62  ประจวบคีรีขันธ์  77
63    นครศรีธรรมราช  80
64           กระบี่  81
65            พังงา  82
66           ภูเก็ต  83
67     สุราษฎร์ธานี  84
68            ระนอง  85
69            ชุมพร  86
70            สงขลา  90
71             สตูล  91
72             ตรัง  92
73           พัทลุง  93
74          ปัตตานี  94
75             ยะลา  95
76         นราธิวาส  96

[77 rows x 2 columns]

In [ ]:
with open('prov_en.json', 'r') as fp:
    jsondataen = json.load(fp)

In [ ]:
en_tab=pd.DataFrame(jsondataen['en']['changwats'])

In [ ]:
en_tab.head()

                       name pid
0                   Bangkok  10
1             Samut Prakarn  11
2                Nonthaburi  12
3              Pathum Thani  13
4  Phra Nakhon Si Ayutthaya  14

In [ ]:
merged_tab_en_th = en_tab.merge(th_tab,how='left',left_on='pid',right_on='pid')

In [ ]:
merged_tab_en_th

                      name_x pid           name_y
0                    Bangkok  10    กรุงเทพมหานคร
1              Samut Prakarn  11      สมุทรปราการ
2                 Nonthaburi  12          นนทบุรี
3               Pathum Thani  13         ปทุมธานี
4   Phra Nakhon Si Ayutthaya  14  พระนครศรีอยุธยา
5                  Ang Thong  15          อ่างทอง
6                   Lop Buri  16           ลพบุรี
7                  Sing Buri  17        สิงห์บุรี
8                   Chai Nat  18           ชัยนาท
9                   Saraburi  19          สระบุรี
10                 Chon Buri  20           ชลบุรี
11                    Rayong  21            ระยอง
12               Chanthaburi  22         จันทบุรี
13                      Trat  23             ตราด
14              Chachoengsao  24       ฉะเชิงเทรา
15              Prachin Buri  25       ปราจีนบุรี
16              Nakhon Nayok  26          นครนายก
17                   Sa kaeo  27          สระแก้ว
18         Nakhon Ratchasima  30       นครราชสีมา
19                  Buri Ram  31        บุรีรัมย์
20                     Surin  32         สุรินทร์
21                 Si Sa Ket  33         ศรีสะเกษ
22          Ubon Ratchathani  34      อุบลราชธานี
23                  Yasothon  35            ยโสธร
24                Chaiyaphum  36          ชัยภูมิ
25             Amnat Charoen  37       อำนาจเจริญ
26                 Bueng Kan  38           บึงกาฬ
27          Nong Bua Lam Phu  39      หนองบัวลำภู
28                 Khon Kaen  40          ขอนแก่น
29                Udon Thani  41         อุดรธานี
..                       ...  ..              ...
47              Nakhon Sawan  60        นครสวรรค์
48               Uthai Thani  61        อุทัยธานี
49            Kamphaeng Phet  62        กำแพงเพชร
50                       Tak  63              ตาก
51                 Sukhothai  64          สุโขทัย
52               Phitsanulok  65         พิษณุโลก
53                   Phichit  66           พิจิตร
54                Phetchabun  67        เพชรบูรณ์
55                Ratchaburi  70          ราชบุรี
56              Kanchanaburi  71        กาญจนบุรี
57               Suphan Buri  72       สุพรรณบุรี
58             Nakhon Pathom  73           นครปฐม
59              Samut Sakhon  74        สมุทรสาคร
60           Samut Songkhram  75      สมุทรสงคราม
61               Phetchaburi  76         เพชรบุรี
62       Prachuap Khiri Khan  77  ประจวบคีรีขันธ์
63       Nakhon Si Thammarat  80    นครศรีธรรมราช
64                     Krabi  81           กระบี่
65                 Phang-nga  82            พังงา
66                    Phuket  83           ภูเก็ต
67               Surat Thani  84     สุราษฎร์ธานี
68                    Ranong  85            ระนอง
69                  Chumphon  86            ชุมพร
70                  Songkhla  90            สงขลา
71                     Satun  91             สตูล
72                     Trang  92             ตรัง
73               Phatthalung  93           พัทลุง
74                   Pattani  94          ปัตตานี
75                      Yala  95             ยะลา
76                Narathiwat  96         นราธิวาส

[77 rows x 3 columns]

In [ ]:
thdata=pd.read_excel('income.xls').iloc[5:86,[0,1]]

In [ ]:
thdata

,ตาราง 9 สัมประสิทธิ์ของความไม่เสมอภาคของการกระจายรายได้ จำแนกตามภาคและจังหวัด ระหว่างปี 2550 - 2556,Unnamed: 1
5,กรุงเทพมหานคร,0.376
6,นนทบุรี,0.278
7,ปทุมธานี,0.274
8,สมุทรปราการ,0.205
9,ภาคกลาง,0.309
10,กาญจนบุรี,0.357
11,จันทบุรี,0.306
12,ฉะเชิงเทรา,0.315
13,ชลบุรี,0.183
14,ชัยนาท,0.364
15,ตราด,0.368
16,นครนายก,0.296
17,นครปฐม,0.191
18,ประจวบคีรีขันธ์,0.348
19,ปราจีนบุรี,0.285
20,พระนครศรีอยุธยา,0.24
21,เพชรบุรี,0.341
22,ระยอง,0.369
23,ราชบุรี,0.305
24,ลพบุรี,0.309
25,สมุทรสงคราม,0.252
26,สมุทรสาคร,0.125
27,สระแก้ว,0.4
28,สระบุรี,0.29
29,สิงห์บุรี,0.376
30,สุพรรณบุรี,0.256
31,อ่างทอง,0.324
32,ภาคเหนือ,0.372
33,กำแพงเพชร,0.306
34,เชียงราย,0.428
...,...,...
56,บึงกาฬ,-
57,บุรีรัมย์,0.355
58,มหาสารคาม,0.355
59,มุกดาหาร,0.356
60,ยโสธร,0.292
61,ร้อยเอ็ด,0.294
62,เลย,0.427
63,ศรีสะเกษ,0.381
64,สกลนคร,0.37
65,สุรินทร์,0.423
66,หนองคาย,0.317
67,หนองบัวลำภู,0.333
68,อุดรธานี,0.408
69,อุบลราชธานี,0.319
70,อำนาจเจริญ,0.304
71,ภาคใต้,0.351
72,กระบี่,0.319
73,ชุมพร,0.314
74,ตรัง,0.319
75,นครศรีธรรมราช,0.442
76,นราธิวาส,0.333
77,ปัตตานี,0.374
78,พังงา,0.215
79,พัทลุง,0.343
80,ภูเก็ต,0.199
81,ยะลา,0.211
82,ระนอง,0.396
83,สงขลา,0.281
84,สตูล,0.296
85,สุราษฎร์ธานี,0.314

In [ ]:
thdata.columns = ['prov', 'val']

In [ ]:
new_col=list()
for d in thdata['prov']:
    new_col.append(d.replace(' ',''))

In [ ]:
thdata['prov']=new_col

In [ ]:
thdata['en_prov']=thdata['prov'].map(merged_tab_en_th.set_index('name_y')['name_x'])

In [ ]:
thdata.dropna(inplace=True)

In [ ]:
thdata=thdata[['en_prov','val']]

In [ ]:
thdata=thdata.drop([56],axis=0) ##buengkan val is not a number

In [ ]:
thdata

                     en_prov    val
5                    Bangkok  0.376
6                 Nonthaburi  0.278
7               Pathum Thani  0.274
8              Samut Prakarn  0.205
10              Kanchanaburi  0.357
11               Chanthaburi  0.306
12              Chachoengsao  0.315
13                 Chon Buri  0.183
14                  Chai Nat  0.364
15                      Trat  0.368
16              Nakhon Nayok  0.296
17             Nakhon Pathom  0.191
18       Prachuap Khiri Khan  0.348
19              Prachin Buri  0.285
20  Phra Nakhon Si Ayutthaya   0.24
21               Phetchaburi  0.341
22                    Rayong  0.369
23                Ratchaburi  0.305
24                  Lop Buri  0.309
25           Samut Songkhram  0.252
26              Samut Sakhon  0.125
27                   Sa kaeo    0.4
28                  Saraburi   0.29
29                 Sing Buri  0.376
30               Suphan Buri  0.256
31                 Ang Thong  0.324
33            Kamphaeng Phet  0.306
34                Chiang Rai  0.428
35                Chiang Mai  0.348
36                       Tak  0.313
..                       ...    ...
54             Nakhon Phanom  0.346
55         Nakhon Ratchasima  0.356
57                  Buri Ram  0.355
58             Maha Sarakham  0.355
59                  Mukdahan  0.356
60                  Yasothon  0.292
61                    Roi Et  0.294
62                      Loei  0.427
63                 Si Sa Ket  0.381
64              Sakon Nakhon   0.37
65                     Surin  0.423
66                 Nong Khai  0.317
67          Nong Bua Lam Phu  0.333
68                Udon Thani  0.408
69          Ubon Ratchathani  0.319
70             Amnat Charoen  0.304
72                     Krabi  0.319
73                  Chumphon  0.314
74                     Trang  0.319
75       Nakhon Si Thammarat  0.442
76                Narathiwat  0.333
77                   Pattani  0.374
78                 Phang-nga  0.215
79               Phatthalung  0.343
80                    Phuket  0.199
81                      Yala  0.211
82                    Ranong  0.396
83                  Songkhla  0.281
84                     Satun  0.296
85               Surat Thani  0.314

[76 rows x 2 columns]

In [ ]:
mapp = folium.Map(location=[14,100], zoom_start=5)

In [ ]:
mapp

In [ ]:
thai_geo = 'thai.json'
mapp.choropleth(geo_data=thai_geo, data=thdata,
             columns=['en_prov','val'],
             key_on='feature.properties.name',
             fill_color='YlGnBu')

In [ ]:
mapp.save('plot_data.html')

In [ ]:
from IPython.display import HTML
HTML('<iframe src=plot_data.html width=700 height=450></iframe>')

In [ ]:
folium.GeoJson(thai_geo).add_to(mapp)